package
{
    public dynamic class Main extends SSF2Asset
    {

        public function Main()
        {
            super();
            register("id", "bomberman");
            register("guid", "5db5bfc3-78aa-4ae8-8208-c39174673a01");
            register("characters", [this.getBomberman()]);
            register("resources", {
                "movieclips":["AudioMC", "bmanFSBomb", "bomberman_fuse", "bomberman", "bomberman_head", "Bomberman_Symbol", "dashicon", "death_bomb", "DeathBombwrapper", "fsmash_bomb", "fsmash_bombwrapper", "iceBomb", "iceBombwrapper", "landboom", "NSpecBomb1Dropped", "NSpecBomb2Dropped", "NSpecBomb3Dropped", "NSpecBomb", "NSpecBombThrown", "RemoteBomb", "RemoteBombwrapper", "rubber_bomb", "dust", "trail_bbm_bair", "trail_bbm_dash", "trail_bbm_dair", "trail_bbm_fair", "trail_bbm_fsmash", "trail_bbm_ftilt", "trail_bbm_jab1", "trail_bbm_jab2", "trail_bbm_jab3", "trail_bbm_nair", "trail_bbm_sspeca", "trail_bbm_sspecg", "trail_bbm_uair", "trail_bbm_utilt", "bomberman_fuse_smoke", "bomber_dust_cloud", "bomber_globalSpark", "bomber_globalSparkle", "bomber_dust_heavy", "bomber_dust_light"],
                "sounds":["bomberman_button", "bomberman_dash", "bomberman_explode", "bomberman_fail", "bomberman_fs_end", "bomberman_fs_sound", "bomberman_jump1", "bomberman_jump2", "bomberman_jumpflip", "bomberman_kick", "bomberman_plant", "bomberman_slide", "bomberman_special_bomb", "bomberman_step1", "bomberman_step2", "bomberman_turn", "bomberman_uspec1", "bomberman_uspec2", "bomberman_uspec3", "bomberman_uspec_end", "bomberman_victory", "BombermanVictory"]
            });
        }

        public function getBomberman():Object
        {
            var _local_1:Object = new Object();
            _local_1 = {
                "classAPI":BombermanExt,
                "statsName":"bomberman",
                "displayName":"Bomberman",
                "linkage_id":"bomberman",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"bomberman_head",
                "seriesIcon":"Bomberman_Symbol",
                "width":20,
                "height":52,
                "jumpSpeed":19.2,
                "jumpSpeedMidair":19.2,
                "jumpStartup":2,
                "shortHopSpeed":11.2,
                "max_jumpSpeed":6.5,
                "groundToAirMultiplier":0.86,
                "dodgeSpeed":15,
                "dodgeDecel":-1.3,
                "gravity":1.7,
                "weight1":97,
                "power":"bomberman",
                "norm_xSpeed":4.1,
                "max_xSpeed":10.7,
                "max_ySpeed":15.1,
                "fastFallSpeed":17.1,
                "accel_start":0.49,
                "accel_start_dash":1.43,
                "accel_rate":2,
                "accel_rate_air":2.5,
                "decel_rate":-1.3,
                "decel_rate_air":-0.23,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":20,
                "tetherGrab":false,
                "roll_speed":28,
                "roll_decay":0.73,
                "getup_roll_delay":5,
                "tech_roll_delay":4,
                "climb_roll_delay":9,
                "itemScaleRatio":1,
                "special_type":1,
                "finalSmashCutin":"bman_fs_cutin",
                "normalStats_id":"bomberman",
                "specialStats_id":null,
                "sounds":{
                    "jump":null,
                    "jump_midair":null,
                    "hurt":null,
                    "hurt2":null,
                    "hurtBad":null,
                    "hurtBad2":null,
                    "dead":null,
                    "dead2":null,
                    "pummel":"brawl_kick_s",
                    "screenko":null,
                    "starko":null,
                    "ledge_grab":null,
                    "winTheme":"BombermanVictory"
                },
                "hurtFrames":3,
                "grabDamage":2,
                "fs_time_limit":390
            };
            var _local_2:Object = new Object();
            _local_2 = {
                "a":{
                    "canFallOff":false,
                    "attackSound1_id":"brawl_swing_s",
                    "attackSound2_id":"brawl_swing_m",
                    "attackSound3_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":1,
                            "effect_id":"effect_lightHit",
                            "hitStun":2,
                            "direction":55,
                            "power":20,
                            "kbConstant":40,
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "a_up":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackSound1_id":"bomberman_explode",
                    "attackSound2_id":"sw_brawl_swing_H",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "priority":5,
                            "hitLag":-2,
                            "effect_id":"effect_firehit_heavy",
                            "direction":110,
                            "power":90,
                            "kbConstant":0,
                            "effectSound":"brawl_fire_l"
                        },
                        "attackBox2":{
                            "damage":3,
                            "priority":5,
                            "hitLag":-2,
                            "effect_id":"effect_firehit_heavy",
                            "direction":110,
                            "power":90,
                            "kbConstant":0,
                            "effectSound":"brawl_fire_l"
                        }
                    }
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "attackSound1_id":"brawl_swing_m",
                    "cpuAttackQueue":"a_up;a_up_tilt;a_forwardsmash;a_down",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":7,
                            "priority":2,
                            "hitLag":-1.2,
                            "effect_id":"effect_hit1",
                            "direction":85,
                            "power":40,
                            "kbConstant":105,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":7,
                            "priority":2,
                            "hitLag":-1.2,
                            "effect_id":"effect_hit1",
                            "direction":85,
                            "power":40,
                            "kbConstant":105,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_forward":{
                    "canFallOff":false,
                    "attackSound1_id":"brawl_swing_l",
                    "cpuAttackQueue":"a_air;a_air_forward;a_air_up;a_air_down",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":2,
                            "direction":30,
                            "reversableAngle":false,
                            "power":70,
                            "kbConstant":80,
                            "effect_id":"effect_heavyHit",
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":3,
                            "effect_id":"effect_hit1",
                            "direction":46,
                            "power":25,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackSound1_id":"bomberman_explode",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":13,
                            "priority":4,
                            "direction":40,
                            "power":84,
                            "kbConstant":75,
                            "effect_id":"effect_firehit_heavy",
                            "effectSound":"brawl_fire_l"
                        },
                        "attackBox2":{
                            "damage":13,
                            "priority":4,
                            "direction":40,
                            "power":84,
                            "kbConstant":75,
                            "effect_id":"effect_firehit_heavy",
                            "effectSound":"brawl_fire_l"
                        }
                    }
                },
                "a_down":{
                    "cancelWhenAirborne":false,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackSound1_id":"bomberman_explode",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":18,
                            "priority":6,
                            "camShake":7,
                            "effect_id":"effect_firehit_heavy",
                            "direction":60,
                            "power":80,
                            "kbConstant":60,
                            "burn":true,
                            "effectSound":"brawl_fire_m"
                        },
                        "attackBox2":{
                            "damage":18,
                            "priority":6,
                            "camShake":7,
                            "effect_id":"effect_firehit_heavy",
                            "direction":60,
                            "power":80,
                            "kbConstant":60,
                            "burn":true,
                            "effectSound":"brawl_fire_m"
                        }
                    }
                },
                "a_air":{
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "attackSound1_id":"brawl_swing_s",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":10,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":80,
                            "power":20,
                            "kbConstant":95,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":10,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":80,
                            "power":20,
                            "kbConstant":95,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_air_up":{
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":11,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":2,
                            "hitLag":-1.2,
                            "effect_id":"effect_heavyHit",
                            "direction":82,
                            "power":33,
                            "kbConstant":104,
                            "effectSound":"whack"
                        },
                        "attackBox2":{
                            "damage":11,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":2,
                            "hitLag":-1.2,
                            "effect_id":"effect_heavyHit",
                            "direction":82,
                            "power":33,
                            "kbConstant":104,
                            "effectSound":"whack"
                        }
                    }
                },
                "a_air_forward":{
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":12,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":2,
                            "hitLag":-1.12,
                            "camShake":2,
                            "effect_id":"effect_heavyHit",
                            "direction":46,
                            "power":50,
                            "kbConstant":90,
                            "effectSound":"brawl_punch_l"
                        },
                        "attackBox2":{
                            "damage":12,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":2,
                            "hitLag":-1.12,
                            "camShake":2,
                            "effect_id":"effect_heavyHit",
                            "direction":46,
                            "power":50,
                            "kbConstant":90,
                            "effectSound":"brawl_punch_l"
                        }
                    }
                },
                "a_air_backward":{
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "attackSound1_id":"brawl_swing_s",
                    "cpuAttackQueue":"a_air_backward",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":10,
                            "hitStun":3,
                            "selfHitStun":1,
                            "hitLag":-1.12,
                            "effect_id":"effect_heavyHit",
                            "direction":40,
                            "power":40,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox2":{
                            "damage":8,
                            "hitStun":3,
                            "selfHitStun":1,
                            "hitLag":-1.12,
                            "effect_id":"effect_heavyHit",
                            "direction":40,
                            "power":40,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_l"
                        }
                    }
                },
                "a_air_down":{
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "attackSound1_id":"brawl_swing_s",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":5,
                            "priority":3,
                            "hitLag":-1.25,
                            "effect_id":"effect_hit1",
                            "direction":75,
                            "reversableAngle":false,
                            "power":28,
                            "kbConstant":0,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox2":{
                            "damage":5,
                            "priority":3,
                            "hitLag":-1.25,
                            "effect_id":"effect_hit1",
                            "direction":75,
                            "reversableAngle":false,
                            "power":28,
                            "kbConstant":0,
                            "effectSound":"brawl_kick_s"
                        }
                    }
                },
                "b":{
                    "cancelWhenAirborne":false,
                    "isLongRangeMove":true,
                    "xSpeedCap":6,
                    "chargetime_max":1,
                    "xSpeedAccelAir":0.5,
                    "holdRepeat":true,
                    "allowTurn":true,
                    "linkFrames":true,
                    "reenableTimer":3,
                    "attackSound1_id":"bomberman_plant",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "b_air":{
                    "cancelWhenAirborne":false,
                    "isLongRangeMove":true,
                    "xSpeedCap":6,
                    "chargetime_max":1,
                    "xSpeedAccelAir":0.5,
                    "holdRepeat":true,
                    "allowRun":true,
                    "allowTurn":true,
                    "linkFrames":true,
                    "reenableTimer":3,
                    "attackSound1_id":"bomberman_plant",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "b_up":{
                    "cancelWhenAirborne":false,
                    "air_ease":7,
                    "xSpeedDecay":0.01,
                    "xSpeedCap":6.5,
                    "allowControl":false,
                    "allowControlGround":false,
                    "canFallOff":true,
                    "isRecoveryMove":true,
                    "attackSound1_id":"bomberman_uspec1",
                    "attackSound2_id":"bomberman_uspec2",
                    "attackSound3_id":"bomberman_uspec3",
                    "attackSound4_id":"bomberman_uspec_end",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":-1,
                            "hitLag":-1,
                            "effect_id":"effect_firehit_heavy",
                            "burn":true,
                            "direction":40,
                            "power":107,
                            "kbConstant":60,
                            "effectSound":"brawl_fire_l"
                        }}
                },
                "b_up_air":{
                    "cancelWhenAirborne":false,
                    "air_ease":7,
                    "xSpeedDecay":0.01,
                    "xSpeedCap":6.5,
                    "allowControl":true,
                    "allowControlGround":false,
                    "isRecoveryMove":true,
                    "attackSound1_id":"bomberman_uspec1",
                    "attackSound2_id":"bomberman_uspec2",
                    "attackSound3_id":"bomberman_uspec3",
                    "attackSound4_id":"bomberman_uspec_end",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":-1,
                            "hitLag":-1,
                            "effect_id":"effect_firehit_heavy",
                            "burn":true,
                            "direction":40,
                            "power":107,
                            "kbConstant":60,
                            "effectSound":"brawl_fire_l"
                        }}
                },
                "b_forward":{
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":-1,
                    "attackSound1_id":"bomberman_kick",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":4,
                            "selfHitStun":3,
                            "effect_id":"effect_hit1",
                            "direction":20,
                            "power":45,
                            "kbConstant":29,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":8,
                            "priority":3,
                            "hitStun":4,
                            "selfHitStun":3,
                            "effect_id":"effect_hit1",
                            "direction":20,
                            "power":45,
                            "kbConstant":29,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "b_forward_air":{
                    "attackSound1_id":"bomberman_kick",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":7,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":3,
                            "effect_id":"effect_hit1",
                            "direction":60,
                            "power":98,
                            "kbConstant":35,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":7,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":3,
                            "effect_id":"effect_hit1",
                            "direction":60,
                            "power":98,
                            "kbConstant":35,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "b_down":{
                    "reenableTimer":70,
                    "disableForCPU":true,
                    "attackSound1_id":"bomberman_fail",
                    "attackSound2_id":"bomberman_button"
                },
                "b_down_air":{
                    "reenableTimer":70,
                    "disableForCPU":true,
                    "attackSound1_id":"bomberman_fail",
                    "attackSound2_id":"bomberman_button"
                },
                "throw_up":{
                    "canFallOff":false,
                    "cpuAttackQueue":"a_air;a_air_up;a_air_down;a_up",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":0,
                            "hitLag":-1.15,
                            "direction":85,
                            "hitStun":0,
                            "selfHitStun":0,
                            "reversableAngle":false,
                            "power":70,
                            "kbConstant":65,
                            "bypassNonGrabbed":true,
                            "effectSound":"melee_throw"
                        }}
                },
                "throw_forward":{
                    "canFallOff":false,
                    "attackSound1_id":"bomberman_slide",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "hitStun":0,
                            "selfHitStun":0,
                            "direction":35,
                            "reversableAngle":false,
                            "power":70,
                            "kbConstant":75,
                            "bypassNonGrabbed":true,
                            "effectSound":"melee_throw"
                        }}
                },
                "throw_back":{
                    "canFallOff":false,
                    "attackBoxes":{"attackBox":{
                            "damage":13,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "direction":155,
                            "reversableAngle":false,
                            "power":80,
                            "kbConstant":55,
                            "bypassNonGrabbed":true,
                            "effectSound":"melee_throw"
                        }}
                },
                "throw_down":{
                    "canFallOff":false,
                    "cpuAttackQueue":"a_air;a_air_down;a_air_up;a_air_forward;a_up_tilt;a_up;a_forwardsmash",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "bypassNonGrabbed":true,
                            "hasEffect":false,
                            "sdiDistance":0,
                            "priority":0,
                            "hitLag":-1.15,
                            "effect_id":"effect_heavyHit",
                            "direction":70,
                            "reversableAngle":false,
                            "power":50,
                            "kbConstant":85,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "crouch_attack":{
                    "resetMovement":true,
                    "canFallOff":false,
                    "attackSound1_id":"bomberman_slide",
                    "cpuAttackQueue":"a_air;a_air_forward;a_air_up",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":2,
                            "hitLag":-1.2,
                            "effect_id":"effect_hit1",
                            "direction":70,
                            "power":45,
                            "kbConstant":105,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "cancelWhenAirborne":false,
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "direction":45,
                            "power":75,
                            "kbConstant":25,
                            "effect_id":"effect_hit1",
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "getup_attack":{
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":0,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":80,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "kirby":{
                    "cancelWhenAirborne":false,
                    "xSpeedCap":2,
                    "chargetime_max":80,
                    "holdRepeat":true,
                    "reenableTimer":3,
                    "attackSound1_id":"bomberman_plant",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "kirby_air":{
                    "cancelWhenAirborne":false,
                    "xSpeedCap":2,
                    "chargetime_max":80,
                    "holdRepeat":true,
                    "reenableTimer":3,
                    "attackSound1_id":"bomberman_plant",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "allowControl":false,
                    "cancelWhenAirborne":false,
                    "air_ease":0,
                    "canFallOff":true,
                    "canUseInAir":true,
                    "ignorePlatformInfluence":true,
                    "attackSound1_id":"bomberman_fs_sound",
                    "attackSound2_id":"bomberman_explode",
                    "attackSound3_id":"bomberman_fail_fs",
                    "attackSound4_id":"bomberman_fs_end",
                    "attackBoxes":{"attackBox":{
                            "damage":18,
                            "priority":-1,
                            "hitStun":2,
                            "hitLag":-0.96,
                            "selfHitStun":0,
                            "direction":50,
                            "power":75,
                            "kbConstant":35,
                            "burn":true,
                            "bypassShield":true,
                            "effect_id":"effect_firehit_heavy",
                            "effectSound":"brawl_fire_l"
                        }}
                },
                "crash":{
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackSound1_id":"whoosh3",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_firehit1",
                            "direction":40,
                            "power":45,
                            "kbConstant":13,
                            "effectSound":"sw_slash"
                        }}
                },
                "item_jab":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_tilt":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_dash":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_smash":{
                    "chargetime_max":40,
                    "chargeClick":true,
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_homerun":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_fan":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_shoot":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "canFallOff":false
                },
                "item_heavyshoot":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "canFallOff":false
                },
                "item_raise":{
                    "maintainSpeed":false,
                    "canFallOff":false
                },
                "item_float":{
                    "maintainSpeed":true,
                    "canFallOff":true
                },
                "item_screw":{
                    "refreshRate":1,
                    "allowControl":true,
                    "air_ease":0,
                    "maintainSpeed":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "attackBoxes":{
                        "attackBox":{
                            "damage":1,
                            "priority":5,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":95,
                            "power":125,
                            "kbConstant":10,
                            "stackKnockback":false,
                            "shock":true,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox2":{
                            "damage":1,
                            "priority":5,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":95,
                            "power":125,
                            "kbConstant":10,
                            "stackKnockback":false,
                            "shock":true,
                            "effectSound":"brawl_kick_s"
                        }
                    }
                },
                "item_firedash":{
                    "allowControl":false,
                    "air_ease":0,
                    "maintainSpeed":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "effect_id":"effect_firehit_heavy",
                            "direction":45,
                            "power":25,
                            "kbConstant":110,
                            "burn":true,
                            "effectSound":"brawl_fire_l"
                        }}
                },
                "item_bubblebounce":{
                    "allowControl":true,
                    "air_ease":-1,
                    "maintainSpeed":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "xSpeedCap":6,
                    "xSpeedAccel":0.75,
                    "xSpeedAccelAir":0.75,
                    "xSpeedDecay":0.99,
                    "xSpeedDecayAir":0.99,
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "effect_id":"effect_waterhit_heavy",
                            "direction":270,
                            "power":20,
                            "kbConstant":80,
                            "effectSound":"sfx_waterhit_m"
                        }}
                }
            };
            var _local_3:Object = {
                "heldbomb":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"NSpecBomb",
                    "inheritPalette":true,
                    "time_max":-1,
                    "surviveDeathBounds":true,
                    "followUser":true,
                    "yoffset":-6,
                    "limit":1,
                    "lockTrajectory":true,
                    "ghost":true,
                    "dangerous":false,
                    "canBePocketed":false
                },
                "bomb1dropped":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"NSpecBomb1Dropped",
                    "inheritPalette":true,
                    "pushCharacters":true,
                    "width":20,
                    "height":20,
                    "time_max":-1,
                    "gravity":1.8,
                    "maxgravity":8,
                    "xoffset":10,
                    "yoffset":-10,
                    "canBePocketed":false,
                    "canBeReversed":false,
                    "noFlip":true,
                    "dangerous":false,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "ignoreChargeDamage":true,
                                "damage":2,
                                "priority":3,
                                "hitStun":5,
                                "hitLag":-1.2,
                                "selfHitStun":5,
                                "direction":75,
                                "power":35,
                                "kbConstant":60,
                                "effectSound":"brawl_kick_s",
                                "effect_id":"effect_lightHit"
                            }}}
                },
                "bomb2dropped":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"NSpecBomb2Dropped",
                    "inheritPalette":true,
                    "pushCharacters":true,
                    "width":30,
                    "height":30,
                    "time_max":-1,
                    "gravity":1.8,
                    "maxgravity":9,
                    "xoffset":10,
                    "yoffset":-15,
                    "canBePocketed":false,
                    "canBeReversed":false,
                    "noFlip":true,
                    "dangerous":false,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "ignoreChargeDamage":true,
                                "damage":3,
                                "priority":3,
                                "hitStun":6,
                                "hitLag":-1.2,
                                "selfHitStun":6,
                                "direction":75,
                                "power":40,
                                "kbConstant":60,
                                "effectSound":"brawl_kick_m",
                                "effect_id":"effect_lightHit"
                            }}}
                },
                "bomb3dropped":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"NSpecBomb3Dropped",
                    "inheritPalette":true,
                    "pushCharacters":true,
                    "width":50,
                    "height":50,
                    "time_max":-1,
                    "gravity":1.8,
                    "maxgravity":10,
                    "xoffset":10,
                    "yoffset":-15,
                    "canBePocketed":false,
                    "canBeReversed":false,
                    "noFlip":true,
                    "dangerous":false,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "ignoreChargeDamage":true,
                                "damage":5,
                                "priority":3,
                                "hitStun":7,
                                "hitLag":-1.2,
                                "selfHitStun":7,
                                "direction":75,
                                "power":45,
                                "kbConstant":60,
                                "effectSound":"brawl_kick_m",
                                "effect_id":"effect_lightHit"
                            }}}
                },
                "FSbomb":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"bmanFSBomb2",
                    "inheritPalette":true,
                    "width":20,
                    "height":20,
                    "time_max":-1,
                    "gravity":1.8,
                    "maxgravity":16,
                    "xoffset":-10,
                    "canBePocketed":false,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "noFlip":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "ignoreChargeDamage":true,
                                "burn":true,
                                "damage":6,
                                "priority":-1,
                                "hitStun":0,
                                "selfHitStun":0,
                                "direction":90,
                                "power":30,
                                "kbConstant":90,
                                "bypassShield":true,
                                "bypassHeavyArmor":true,
                                "bypassSuperArmor":true,
                                "effect_id":"effect_firehit_heavy",
                                "effectSound":"brawl_fire_l"
                            }}}
                },
                "medFSbomb":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"bmanFSBomb3",
                    "inheritPalette":true,
                    "width":20,
                    "height":20,
                    "time_max":-1,
                    "gravity":1.8,
                    "maxgravity":16,
                    "xoffset":-10,
                    "canBePocketed":false,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "noFlip":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "ignoreChargeDamage":true,
                                "burn":true,
                                "damage":8,
                                "priority":-1,
                                "hitStun":0,
                                "selfHitStun":0,
                                "direction":90,
                                "power":45,
                                "kbConstant":100,
                                "bypassShield":true,
                                "bypassHeavyArmor":true,
                                "bypassSuperArmor":true,
                                "effect_id":"effect_firehit_heavy",
                                "effectSound":"brawl_fire_l"
                            }}}
                },
                "bigFSbomb":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"bmanFSBomb",
                    "inheritPalette":true,
                    "width":50,
                    "height":50,
                    "time_max":-1,
                    "gravity":1.8,
                    "maxgravity":18,
                    "yoffset":30,
                    "canBePocketed":false,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "noFlip":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "ignoreChargeDamage":true,
                                "burn":true,
                                "damage":10,
                                "priority":-1,
                                "hitStun":1,
                                "hitLag":-1.2,
                                "selfHitStun":0,
                                "direction":90,
                                "power":65,
                                "kbConstant":110,
                                "bypassShield":true,
                                "bypassHeavyArmor":true,
                                "bypassSuperArmor":true,
                                "effect_id":"effect_firehit_heavy",
                                "effectSound":"brawl_fire_l"
                            }}}
                },
                "crossFSbomb":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"bmanFSBomb4",
                    "inheritPalette":true,
                    "width":50,
                    "height":50,
                    "time_max":-1,
                    "gravity":1.8,
                    "maxgravity":18,
                    "yoffset":-40,
                    "canBePocketed":false,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "noFlip":true,
                    "attack_idle":{"attackBoxes":{
                            "attackBox":{
                                "ignoreChargeDamage":true,
                                "burn":true,
                                "damage":35,
                                "priority":-1,
                                "hitStun":12,
                                "selfHitStun":0,
                                "direction":90,
                                "power":122,
                                "kbConstant":25,
                                "bypassShield":true,
                                "bypassHeavyArmor":true,
                                "bypassSuperArmor":true,
                                "effect_id":"effect_firehit_heavy",
                                "effectSound":"brawl_fire_l"
                            },
                            "attackBox2":{
                                "ignoreChargeDamage":true,
                                "burn":true,
                                "damage":35,
                                "priority":-1,
                                "hitStun":12,
                                "selfHitStun":0,
                                "direction":90,
                                "power":122,
                                "kbConstant":25,
                                "bypassShield":true,
                                "bypassHeavyArmor":true,
                                "bypassSuperArmor":true,
                                "effect_id":"effect_firehit_heavy",
                                "effectSound":"brawl_fire_l"
                            }
                        }}
                },
                "kirbyBManBomb":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"NSpecBombThrown",
                    "inheritPalette":true,
                    "width":20,
                    "height":20,
                    "time_max":75,
                    "xspeed":8,
                    "yspeed":-10,
                    "gravity":1.8,
                    "maxgravity":12,
                    "xoffset":10,
                    "yoffset":-45,
                    "canBeAbsorbed":false,
                    "noFlip":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "ignoreChargeDamage":true,
                                "burn":true,
                                "damage":10,
                                "priority":-1,
                                "hitStun":1,
                                "selfHitStun":0,
                                "direction":90,
                                "power":35,
                                "kbConstant":60,
                                "effect_id":"effect_firehit_light",
                                "effectSound":"brawl_fire_l"
                            }}}
                }
            };
            var _local_4:Object;
            return {
                "cData":_local_1,
                "aData":_local_2,
                "pData":_local_3,
                "iData":_local_4
            };
        }


    }
}

