package
{
    public dynamic class Main extends SSF2Asset
    {

        public var stance:chibi_dashAttackTrail;

        public function Main()
        {
            super();
            register("id", "chibirobo");
            register("guid", "c51a5173-a652-4c9a-9410-87b46e9702c3");
            register("characters", [this.getChibiRobo()]);
            register("resources", {
                "movieclips":["chibirobo", "telly_vision", "chibi_dair_proj", "chibi_dashattack_proj", "chibi_dsmash_proj", "chibi_dtilt_proj", "chibi_fsmash_proj", "chibi_ftilt_proj", "chibi_nair_proj", "chibi_uair_proj", "chibi_usmash_proj", "chibi_lazor", "gigarobo", "chibi_head", "chibi_icon", "bairbubbles", "bubbleExplosion", "floorTwinkle", "effect_fastFall", "dthrow_bubbles", "soapBubbles", "chibi_uthrowEffect"],
                "sounds":["chibi_AStep", "chibi_BStep", "chibi_Bend", "chibi_Blaster", "chibi_dSpec_grab", "chibi_DThrow", "chibi_FSmash", "chibi_FSmash2", "chibi_rankup_victory", "chibi_step1", "chibi_Teleport", "chibiVictory", "chibi_CloseHead", "chibi_Confirm", "chibi_DStep", "chibi_DropPlug", "chibi_EStep", "chibi_GStep", "giga_step", "giga_summon", "giga_exit", "giga_voice1", "giga_voice7", "giga_voice2", "giga_voice3", "giga_voice4", "giga_voice5", "giga_voice6", "chibi_GrabRope", "chibi_ItemOnHead", "chibi_Jump", "chibi_LedgeClimb", "chibi_OpenHead", "chibi_PichuAttack", "chibi_pickplug", "chibi_PikaShock", "chibi_PlugIn", "chibi_Prop_Quick", "chibi_Prop_Release", "run_start", "chibi_Spoon1", "chibi_Spoon2", "chibi_Spoon3", "chibi_Spoon4", "chibi_squirter", "chibi_StoreItem", "chibi_Toothbrush", "chibi_Turn"]
            });
        }

        public function getChibiRobo():Object
        {
            var _local_1:Object = new Object();
            _local_1 = {
                "statsName":"chibirobo",
                "classAPI":ChibiExt,
                "displayName":"Chibi-Robo",
                "linkage_id":"chibirobo",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"chibi_head",
                "seriesIcon":"chibi_icon",
                "width":31,
                "height":45,
                "revivalEffect":null,
                "power":"chibirobo",
                "maxShieldSize":1.25,
                "max_projectile":60,
                "tetherGrab":false,
                "itemScaleRatio":0.769230769230769,
                "special_type":1,
                "finalSmashCutin":"chibi_fs_cutin",
                "normalStats_id":"chibirobo",
                "specialStats_id":null,
                "jumpSpeed":17.8,
                "jumpSpeedMidair":17.8,
                "jumpStartup":2,
                "shortHopSpeed":13,
                "max_jumpSpeed":6.5,
                "groundToAirMultiplier":0.8,
                "gravity":1.6,
                "max_ySpeed":13.5,
                "fastFallSpeed":16,
                "holdJump":false,
                "max_jump":1,
                "weight1":82,
                "norm_xSpeed":3.5,
                "max_xSpeed":10,
                "accel_start":0.572,
                "accel_start_dash":1.57,
                "accel_rate":1,
                "accel_rate_air":0.7,
                "decel_rate":-1.5,
                "decel_rate_air":-0.15,
                "dodgeSpeed":17,
                "dodgeDecel":-1.5,
                "roll_speed":25,
                "roll_decay":0.765,
                "getup_roll_delay":5,
                "tech_roll_delay":4,
                "climb_roll_delay":9,
                "sounds":{
                    "jump":"chibi_Jump",
                    "jump_midair":"chibi_Jump",
                    "hurt":null,
                    "hurt2":null,
                    "hurtBad":null,
                    "hurtBad2":null,
                    "dead":null,
                    "dead2":null,
                    "pummel":"brawl_zap_s",
                    "screenko":null,
                    "starko":null,
                    "ledge_grab":null,
                    "winTheme":"chibiVictory"
                },
                "hurtFrames":4,
                "grabDamage":2.5,
                "fs_time_limit":500
            };
            var _local_2:Object = new Object();
            _local_2 = {
                "a":{
                    "canFallOff":false,
                    "attackSound1_id":"brawl_swing_s",
                    "attackSound2_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":1,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":45,
                            "power":15,
                            "kbConstant":25,
                            "stackKnockback":false,
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "a_up":{
                    "refreshRate":30,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackSound1_id":"chibi_PichuAttack",
                    "attackSound2_id":"chibi_PlugIn",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "stackKnockback":false,
                            "effectSound":"brawl_zap_m",
                            "shock":true,
                            "priority":4,
                            "effect_id":"effect_elechit_light",
                            "direction":110,
                            "power":0,
                            "weightKB":60,
                            "kbConstant":100,
                            "effectSound":"brawl_zap_s"
                        }}
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "attackSound1_id":"chibi_ItemOnHead",
                    "cpuAttackQueue":"a_up;a_up_tilt;a_air;a_air_forward;a_air_backward;a_air_up;a_air_down;throw_down",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":9.5,
                            "priority":2,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":98,
                            "power":30,
                            "kbConstant":127,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":9.5,
                            "priority":2,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":98,
                            "power":30,
                            "kbConstant":127,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_forward":{
                    "canFallOff":false,
                    "attackSound1_id":"chibi_GrabRope",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":6,
                            "priority":2,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_elechit_light",
                            "direction":75,
                            "power":57,
                            "kbConstant":85,
                            "effectSound":"brawl_zap_s"
                        },
                        "attackBox2":{
                            "damage":7,
                            "priority":3,
                            "shock":true,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_elechit_light",
                            "direction":75,
                            "power":57,
                            "kbConstant":85,
                            "effectSound":"brawl_zap_m"
                        }
                    }
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "refreshRate":50,
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":3,
                            "hitLag":-1.1,
                            "effect_id":"effect_elechit_light",
                            "direction":40,
                            "power":15,
                            "kbConstant":130,
                            "effectSound":"brawl_zap_s"
                        }}
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackSound1_id":"chibi_FSmash",
                    "attackSound2_id":"chibi_FSmash2",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":3,
                            "shock":true,
                            "reversableAngle":false,
                            "effect_id":"effect_elechit_light",
                            "direction":340,
                            "power":0,
                            "weightKB":60,
                            "kbConstant":100,
                            "effectSound":"brawl_zap_s",
                            "hitLag":-0.4
                        }}
                },
                "a_down":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackSound1_id":"chibi_PlugIn",
                    "attackSound2_id":"chibi_PikaShock",
                    "attackBoxes":{
                        "attackBox":{
                            "shock":true,
                            "damage":16,
                            "priority":-1,
                            "effect_id":"effect_elechit_heavy",
                            "direction":90,
                            "power":55,
                            "kbConstant":110,
                            "effectSound":"brawl_zap_l"
                        },
                        "attackBox2":{
                            "shock":true,
                            "damage":13,
                            "priority":-1,
                            "effect_id":"effect_elechit_light",
                            "direction":60,
                            "power":25,
                            "kbConstant":110,
                            "effectSound":"brawl_zap_m"
                        }
                    }
                },
                "a_air":{
                    "allowControl":true,
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":10,
                            "priority":4,
                            "shock":true,
                            "hitLag":-1.1,
                            "effect_id":"effect_hit2",
                            "direction":32,
                            "power":40,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":10,
                            "priority":3,
                            "hitLag":-1.1,
                            "effect_id":"effect_hit2",
                            "direction":32,
                            "power":40,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_air_up":{
                    "allowControl":true,
                    "attackBoxes":{
                        "attackBox":{
                            "damage":12,
                            "priority":4,
                            "hitStun":-1,
                            "selfHitStun":-1,
                            "effect_id":"effect_elechit_heavy",
                            "direction":40,
                            "power":54,
                            "kbConstant":110,
                            "effectSound":"brawl_zap_l",
                            "shock":true
                        },
                        "attackBox2":{
                            "damage":9,
                            "priority":4,
                            "effect_id":"effect_elechit_heavy",
                            "direction":40,
                            "power":50,
                            "kbConstant":95,
                            "effectSound":"brawl_zap_l",
                            "shock":true
                        }
                    }
                },
                "a_air_forward":{
                    "allowControl":true,
                    "attackSound1_id":"sw_brawl_swing_M",
                    "cpuAttackQueue":"a_air;a_air_down",
                    "attackBoxes":{"attackBox":{
                            "damage":9.5,
                            "priority":3,
                            "effect_id":"effect_swordSlash",
                            "direction":60,
                            "power":40,
                            "kbConstant":105,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_air_backward":{
                    "allowControl":true,
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":4,
                            "effect_id":"effect_waterhit_heavy",
                            "direction":40,
                            "power":42,
                            "kbConstant":105,
                            "effectSound":"sfx_waterhit_l"
                        }}
                },
                "a_air_down":{
                    "allowControl":true,
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":15,
                            "priority":5,
                            "effect_id":"effect_elechit_heavy",
                            "direction":270,
                            "power":30,
                            "kbConstant":60,
                            "shock":true,
                            "effectSound":"brawl_zap_m"
                        }}
                },
                "b":{
                    "isLongRangeMove":true,
                    "attackSound1_id":"chibi_Spoon1",
                    "attackSound2_id":"chibi_Spoon2",
                    "attackSound3_id":"chibi_Spoon3",
                    "attackSound4_id":"chibi_Spoon4",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "direction":10,
                            "power":30,
                            "kbConstant":16,
                            "effectSound":"brawl_magic_s"
                        }}
                },
                "b_air":{
                    "isLongRangeMove":true,
                    "allowFastFall":false,
                    "attackSound1_id":"chibi_Spoon1",
                    "attackSound2_id":"chibi_Spoon2",
                    "attackSound3_id":"chibi_Spoon3",
                    "attackSound4_id":"chibi_Spoon4",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "selfHitStun":0,
                            "direction":10,
                            "power":30,
                            "kbConstant":16,
                            "effectSound":"brawl_magic_s"
                        }}
                },
                "b_up":{
                    "refreshRate":2,
                    "cancelWhenAirborne":false,
                    "allowControl":false,
                    "allowFastFall":false,
                    "xSpeedAccelAir":2,
                    "xSpeedCap":3.4,
                    "attackSound1_id":"chibi_Prop_Release",
                    "attackSound2_id":"chibi_Prop_Quick",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":1,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":85,
                            "kbConstant":50,
                            "stackKnockback":false,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "b_up_air":{
                    "refreshRate":2,
                    "cancelWhenAirborne":false,
                    "allowControl":false,
                    "allowFastFall":false,
                    "xSpeedAccelAir":1.1,
                    "xSpeedCap":5.87,
                    "allowControl":true,
                    "isRecoveryMove":true,
                    "attackSound1_id":"chibi_Prop_Release",
                    "attackSound2_id":"chibi_Prop_Quick",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":1,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":85,
                            "kbConstant":50,
                            "stackKnockback":false,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "b_forward":{
                    "cancelSoundOnEnd":true,
                    "canFallOff":true,
                    "air_ease":2,
                    "cancelWhenAirborne":false,
                    "attackSound1_id":"chibi_Toothbrush",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":3,
                            "effect_id":"effect_waterhit_light",
                            "direction":20,
                            "power":40,
                            "kbConstant":30,
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "b_forward_air":{
                    "cancelSoundOnEnd":true,
                    "isHorizontalRecoveryMove":true,
                    "canFallOff":true,
                    "air_ease":2,
                    "cancelWhenAirborne":false,
                    "attackSound1_id":"chibi_Toothbrush",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":3,
                            "effect_id":"effect_waterhit_light",
                            "direction":20,
                            "power":40,
                            "kbConstant":30,
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "b_down":{
                    "chargetime_max":100,
                    "cancelWhenAirborne":false,
                    "allowControl":true,
                    "allowControlGround":false,
                    "allowFastFall":false,
                    "attackSound1_id":"chibi_pickplug",
                    "attackSound2_id":"chibi_dSpec_grab",
                    "attackSound3_id":"chibi_Confirm",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "power":20,
                            "kbConstant":16,
                            "effectSound":"kick"
                        }}
                },
                "b_down_air":{
                    "chargetime_max":100,
                    "cancelWhenAirborne":false,
                    "allowControl":true,
                    "allowControlGround":false,
                    "attackSound1_id":"chibi_pickplug",
                    "attackSound2_id":"chibi_dSpec_grab",
                    "attackSound3_id":"chibi_Confirm",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "power":20,
                            "kbConstant":16,
                            "effectSound":"kick"
                        }}
                },
                "throw_up":{
                    "canFallOff":false,
                    "attackSound1_id":"chibi_squirter",
                    "cpuAttackQueue":"a_air_up;a_air",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "bypassGrabbed":true,
                            "direction":45,
                            "power":60,
                            "kbConstant":100,
                            "effectSound":"sfx_waterhit_ss",
                            "effect_id":"effect_waterhit_light"
                        },
                        "attackBox2":{
                            "damage":3,
                            "bypassNonGrabbed":true,
                            "hitLag":-1.12,
                            "hasEffect":false,
                            "priority":0,
                            "effect_id":"effect_waterhit_light",
                            "direction":65,
                            "reversableAngle":false,
                            "power":55,
                            "kbConstant":50,
                            "effectSound":"sfx_waterhit_ss"
                        }
                    }
                },
                "throw_forward":{
                    "refreshRate":10,
                    "canFallOff":false,
                    "attackSound1_id":null,
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "bypassGrabbed":true,
                            "direction":45,
                            "power":60,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_l",
                            "effect_id":"effect_heavyHit"
                        },
                        "attackBox2":{
                            "damage":9,
                            "bypassNonGrabbed":true,
                            "priority":0,
                            "effect_id":"effect_heavyHit",
                            "direction":42,
                            "reversableAngle":false,
                            "power":60,
                            "kbConstant":55,
                            "effectSound":"brawl_kick_l"
                        }
                    }
                },
                "throw_back":{
                    "canFallOff":false,
                    "attackSound1_id":null,
                    "cpuAttackQueue":"a_air;throw_back;throw_down;a_air_backward",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":0,
                            "effect_id":"effect_heavyHit",
                            "direction":135,
                            "reversableAngle":false,
                            "power":60,
                            "kbConstant":75,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "throw_down":{
                    "refreshRate":3,
                    "canFallOff":false,
                    "attackSound1_id":"chibi_DThrow",
                    "cpuAttackQueue":"a_up_tilt;a_up;a_down;a_air;a_air_up;a_air_backward",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "bypassGrabbed":true,
                            "direction":45,
                            "power":60,
                            "kbConstant":100,
                            "effectSound":"sfx_waterhit_ss",
                            "effect_id":"effect_waterhit_light"
                        },
                        "attackBox2":{
                            "damage":2,
                            "bypassNonGrabbed":true,
                            "hasEffect":false,
                            "priority":0,
                            "effect_id":"effect_waterhit_light",
                            "direction":100,
                            "reversableAngle":false,
                            "power":80,
                            "kbConstant":30,
                            "effectSound":"sfx_waterhit_ss"
                        }
                    }
                },
                "crouch_attack":{
                    "canFallOff":false,
                    "attackVoice1_id":null,
                    "attackSound1_id":"chibi_DropPlug",
                    "cpuAttackQueue":"a_forward_tilt;a_forwardsmash;a_air;a_air_forward",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":2,
                            "hitLag":-1.1,
                            "effect_id":"effect_lightHit",
                            "direction":57,
                            "power":30,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_s"
                        }}
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "direction":45,
                            "power":75,
                            "kbConstant":25,
                            "shock":true,
                            "effect_id":"effect_hit2",
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "getup_attack":{
                    "resetMovement":true,
                    "canFallOff":false,
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":8,
                            "priority":4,
                            "effect_id":"effect_hit1",
                            "direction":45,
                            "power":80,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":8,
                            "priority":4,
                            "effect_id":"effect_hit1",
                            "direction":45,
                            "power":80,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "kirby":{
                    "cancelSoundOnEnd":true,
                    "allowControl":true,
                    "chargetime_max":72,
                    "charge_retain":true,
                    "holdRepeat":true,
                    "chargeInAir":false,
                    "reenableTimer":3,
                    "useChargeBar":false,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "direction":10,
                            "power":30,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "kirby_air":{
                    "cancelSoundOnEnd":true,
                    "allowControl":true,
                    "allowControlGround":false,
                    "chargetime_max":72,
                    "charge_retain":true,
                    "holdRepeat":true,
                    "chargeInAir":false,
                    "reenableTimer":3,
                    "useChargeBar":false,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "selfHitStun":0,
                            "direction":10,
                            "power":30,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "air_ease":0,
                    "canUseInAir":true,
                    "attackSound1_id":"giga_summon",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":-1,
                            "selfHitStun":-1,
                            "direction":0,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":null
                        }}
                },
                "item_jab":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_tilt":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_dash":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_smash":{
                    "chargetime_max":40,
                    "chargeClick":true,
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_homerun":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_fan":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_shoot":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "canFallOff":false
                },
                "item_heavyshoot":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "canFallOff":false
                },
                "item_raise":{
                    "maintainSpeed":false,
                    "canFallOff":false
                },
                "item_float":{
                    "maintainSpeed":true,
                    "canFallOff":true
                },
                "item_screw":{
                    "refreshRate":1,
                    "allowControl":true,
                    "air_ease":0,
                    "maintainSpeed":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "attackBoxes":{
                        "attackBox":{
                            "damage":1,
                            "priority":5,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":95,
                            "power":125,
                            "kbConstant":10,
                            "stackKnockback":false,
                            "shock":true,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox2":{
                            "damage":1,
                            "priority":5,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":95,
                            "power":125,
                            "kbConstant":10,
                            "stackKnockback":false,
                            "shock":true,
                            "effectSound":"brawl_kick_s"
                        }
                    }
                },
                "item_firedash":{
                    "allowControl":false,
                    "air_ease":0,
                    "maintainSpeed":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "effect_id":"effect_firehit_heavy",
                            "direction":45,
                            "power":25,
                            "kbConstant":110,
                            "burn":true,
                            "effectSound":"brawl_fire_l"
                        }}
                },
                "item_bubblebounce":{
                    "allowControl":true,
                    "air_ease":-1,
                    "maintainSpeed":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "xSpeedCap":6,
                    "xSpeedAccel":0.75,
                    "xSpeedAccelAir":0.75,
                    "xSpeedDecay":0.99,
                    "xSpeedDecayAir":0.99,
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "effect_id":"effect_waterhit_heavy",
                            "direction":270,
                            "power":20,
                            "kbConstant":80,
                            "effectSound":"sfx_waterhit_m"
                        }}
                }
            };
            var _local_3:Object = {
                "chibi_blaster":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"chibi_lazor",
                    "rotate":true,
                    "time_max":11,
                    "xspeed":24,
                    "xoffset":30,
                    "yoffset":-24,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":1.5,
                                "hasEffect":true,
                                "priority":-1,
                                "shock":true,
                                "hitLag":-0.7,
                                "hitStun":1,
                                "effect_id":"effect_elechit_light",
                                "direction":60,
                                "power":11,
                                "kbConstant":55,
                                "effectSound":null
                            }}}
                },
                "telly_vision":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"telly_vision",
                    "canBeReversed":false,
                    "ghost":true,
                    "dangerous":false,
                    "limit":1,
                    "time_max":-1,
                    "xoffset":30,
                    "yoffset":-24,
                    "surviveDeathBounds":true,
                    "inheritPalette":true
                },
                "chibi_ftiltProj":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"chibi_ftilt_proj",
                    "width":30,
                    "height":36,
                    "limitOverwrite":true,
                    "time_max":600,
                    "gravity":0,
                    "maxgravity":0,
                    "canBeReversed":false
                },
                "chibi_dtiltProj":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"chibi_dtilt_proj",
                    "width":30,
                    "height":36,
                    "limitOverwrite":true,
                    "time_max":600,
                    "gravity":0,
                    "maxgravity":0,
                    "canBeReversed":false
                },
                "chibi_fsmashProj":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"chibi_fsmash_proj",
                    "width":30,
                    "height":36,
                    "limitOverwrite":true,
                    "time_max":600,
                    "gravity":0,
                    "maxgravity":0,
                    "canBeReversed":false
                },
                "chibi_usmashProj":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"chibi_usmash_proj",
                    "width":30,
                    "height":36,
                    "limitOverwrite":true,
                    "time_max":600,
                    "gravity":0,
                    "maxgravity":0,
                    "canBeReversed":false
                },
                "chibi_dsmashProj":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"chibi_dsmash_proj",
                    "width":30,
                    "height":36,
                    "limitOverwrite":true,
                    "time_max":600,
                    "gravity":0,
                    "maxgravity":0,
                    "canBeReversed":false
                },
                "chibi_nairProj":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"chibi_nair_proj",
                    "width":30,
                    "height":36,
                    "limitOverwrite":true,
                    "time_max":600,
                    "gravity":0,
                    "maxgravity":0,
                    "canBeReversed":false
                },
                "chibi_dairProj":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"chibi_dair_proj",
                    "width":30,
                    "height":36,
                    "limitOverwrite":true,
                    "time_max":600,
                    "gravity":0,
                    "maxgravity":0,
                    "canBeReversed":false
                },
                "chibi_uairProj":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"chibi_uair_proj",
                    "width":30,
                    "height":36,
                    "limitOverwrite":true,
                    "time_max":600,
                    "gravity":0,
                    "maxgravity":0,
                    "canBeReversed":false
                },
                "gigarobo":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"gigarobo",
                    "height":350,
                    "limit":1,
                    "canBePocketed":false,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "time_max":999,
                    "gravity":2,
                    "maxgravity":13,
                    "surviveDeathBounds":false,
                    "inheritPalette":true,
                    "attack_idle":{"attackBoxes":{
                            "attackBox":{
                                "damage":12,
                                "hasEffect":true,
                                "priority":-1,
                                "hitStun":5,
                                "hitLag":-1,
                                "selfHitStun":4,
                                "effect_id":"effect_heavyHit",
                                "direction":270,
                                "power":80,
                                "kbConstant":90,
                                "bypassShield":true,
                                "bypassHeavyArmor":true,
                                "bypassSuperArmor":true,
                                "pitfall":20
                            },
                            "attackBox2":{
                                "damage":12,
                                "hasEffect":true,
                                "priority":-1,
                                "hitStun":5,
                                "hitLag":-1,
                                "selfHitStun":4,
                                "effect_id":"effect_heavyHit",
                                "direction":270,
                                "power":80,
                                "kbConstant":90,
                                "bypassShield":true,
                                "bypassHeavyArmor":true,
                                "bypassSuperArmor":true,
                                "pitfall":20
                            }
                        }}
                }
            };
            var _local_4:Object;
            return {
                "cData":_local_1,
                "aData":_local_2,
                "pData":_local_3,
                "iData":_local_4
            };
        }


    }
}

