package
{
    public dynamic class Main extends SSF2Asset
    {

        public function Main()
        {
            super();
            register("id", "simon");
            register("guid", "0ff43725-06ab-4c74-9637-8467b9f3c286");
            register("resources", {
                "movieclips":["simon_head", "castlevania_icon", "simon"],
                "sounds":[]
            });
            register("characters", [this.getSimon()]);
        }

        public function getSimon():Object
        {
            var _local_1:Object = new Object();
            _local_1 = {
                "classAPI":SimonExt,
                "statsName":"simon",
                "displayName":"Simon",
                "linkage_id":"simon",
                "linkage_id_special":null,
                "thumbnail":"simon_head",
                "seriesIcon":"castlevania_icon",
                "width":30,
                "height":58,
                "jumpSpeed":17,
                "jumpSpeedMidair":18,
                "jumpStartup":2,
                "shortHopSpeed":12,
                "max_jumpSpeed":7,
                "groundToAirMultiplier":0.941,
                "dodgeSpeed":15,
                "dodgeDecel":-0.95,
                "gravity":1.65,
                "weight1":110,
                "power":"simon",
                "norm_xSpeed":4,
                "max_xSpeed":8.5,
                "max_ySpeed":12.5,
                "fastFallSpeed":17,
                "accel_start":0.5,
                "accel_start_dash":1.1,
                "accel_rate":1.1,
                "accel_rate_air":1,
                "decel_rate":-0.95,
                "decel_rate_air":-0.2,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":10,
                "tetherGrab":false,
                "roll_speed":40,
                "roll_decay":0.63,
                "getup_roll_delay":6,
                "tech_roll_delay":4,
                "climb_roll_delay":8,
                "itemScaleRatio":0.833333333333333,
                "special_type":1,
                "shield_scale":1.2,
                "shield_x_offset":10,
                "shield_y_offset":-3,
                "normalStats_id":"simon",
                "finalSmashCutin":"simon_fs_cutin",
                "specialStats_id":null,
                "sounds":{
                    "jump":null,
                    "jump_midair":null,
                    "hurt":"ssf2_snd_vfx_simon_hurt01",
                    "hurt2":"ssf2_snd_vfx_simon_hurt02",
                    "hurtBad":"ssf2_snd_vfx_simon_hurtbad01",
                    "hurtBad2":"ssf2_snd_vfx_simon_hurtbad02",
                    "dead":"ssf2_snd_vfx_simon_dead01",
                    "dead2":"ssf2_snd_vfx_simon_dead02",
                    "pummel":"brawl_kick_s",
                    "screenko":"ssf2_snd_vfx_simon_hurt01",
                    "starko":"ssf2_snd_vfx_simon_starKO",
                    "ledge_grab":"ssf2_snd_vfx_simon_edgeGrab",
                    "winTheme":"CastlevaniaVictory"
                },
                "hurtFrames":5,
                "grabDamage":2
            };
            var _local_2:Object = new Object();
            _local_2 = {
                "a":{
                    "canFallOff":false,
                    "attackSound1_id":"ssf2_snd_sfx_simon_attack_swing_s",
                    "attackSound2_id":"ssf2_snd_sfx_simon_attack_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":6,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":35,
                            "kbConstant":88,
                            "effectSound":"ssf2_snd_sfx_simon_attack_hit_s"
                        },
                        "attackBox2":{
                            "damage":4,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":20,
                            "kbConstant":70,
                            "effectSound":"ssf2_snd_sfx_simon_attack_hit_s"
                        }
                    }
                },
                "a_up":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"ssf2_snd_vfx_simon_usmash",
                    "attackSound1_id":"ssf2_snd_sfx_simon_attack_swing_m",
                    "attackSound2_id":"ssf2_snd_sfx_simon_attack_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":5,
                            "priority":5,
                            "chargedPriority":-1,
                            "hitStun":2,
                            "hitLag":-1.3,
                            "effect_id":"effect_hit2",
                            "selfHitStun":2,
                            "direction":110,
                            "canDI":false,
                            "power":60,
                            "weightKB":50,
                            "kbConstant":0,
                            "effectSound":"ssf2_snd_sfx_simon_attack_hit_l"
                        },
                        "attackBox2":{
                            "damage":5,
                            "priority":5,
                            "chargedPriority":-1,
                            "hitStun":2,
                            "hitLag":-1.3,
                            "effect_id":"effect_hit2",
                            "selfHitStun":2,
                            "direction":110,
                            "canDI":false,
                            "power":60,
                            "weightKB":50,
                            "kbConstant":0,
                            "effectSound":"ssf2_snd_sfx_simon_attack_hit_l"
                        }
                    }
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"ssf2_snd_vfx_simon_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_simon_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_simon_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_simon_attack04",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":2,
                            "hitLag":-1.12,
                            "effect_id":"effect_hit1",
                            "direction":88,
                            "power":70,
                            "kbConstant":85,
                            "effectSound":"brawl_punch_m"
                        },
                        "attackBox2":{
                            "damage":8,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":2,
                            "hitLag":-1.12,
                            "effect_id":"effect_hit1",
                            "direction":88,
                            "power":70,
                            "kbConstant":85,
                            "effectSound":"brawl_punch_m"
                        }
                    }
                },
                "a_forward":{
                    "resetMovement":true,
                    "refreshRate":3,
                    "canFallOff":false,
                    "attackVoice1_id":"ssf2_snd_vfx_simon_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_simon_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_simon_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_simon_attack04",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":1,
                            "reversableAngle":false,
                            "priority":3,
                            "effect_id":"effect_swordHit",
                            "direction":30,
                            "power":40,
                            "kbConstant":50,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":1,
                            "reversableAngle":false,
                            "priority":3,
                            "effect_id":"effect_swordHit",
                            "direction":30,
                            "power":40,
                            "kbConstant":50,
                            "effectSound":"sw_brawl_hit_S"
                        }
                    }
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "allowFastFall":false,
                    "attackVoice1_id":"ssf2_snd_vfx_simon_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_simon_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_simon_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_simon_attack04",
                    "attackSound1_id":"ssf2_snd_sfx_simon_attack_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":6,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":50,
                            "power":60,
                            "kbConstant":65,
                            "effectSound":"ssf2_snd_sfx_simon_attack_hit_m"
                        },
                        "attackBox2":{
                            "damage":9,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":50,
                            "power":60,
                            "kbConstant":65,
                            "effectSound":"ssf2_snd_sfx_simon_attack_hit_m"
                        }
                    }
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"ssf2_snd_vfx_simon_fsmash",
                    "attackSound1_id":"ssf2_snd_sfx_simon_attack_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":12,
                            "priority":-1,
                            "effect_id":"effect_hit2",
                            "direction":40,
                            "power":56,
                            "kbConstant":105,
                            "effectSound":"ssf2_snd_sfx_simon_attack_hit_l"
                        },
                        "attackBox2":{
                            "damage":16,
                            "priority":-1,
                            "effect_id":"effect_hit2",
                            "direction":40,
                            "power":56,
                            "kbConstant":105,
                            "effectSound":"ssf2_snd_sfx_simon_attack_hit_l"
                        }
                    }
                },
                "a_down":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"ssf2_snd_vfx_simon_dsmash",
                    "attackSound1_id":"ssf2_snd_sfx_simon_attack_swing_m",
                    "attackSound2_id":"ssf2_snd_sfx_simon_attack_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":7,
                            "hitStun":-1.05,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":150,
                            "power":42,
                            "kbConstant":85,
                            "reversableAngle":false,
                            "effectSound":"ssf2_snd_sfx_simon_attack_hit_l"
                        }}
                },
                "a_air":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"ssf2_snd_vfx_simon_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_simon_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_simon_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_simon_attack04",
                    "attackSound1_id":"ssf2_snd_sfx_simon_attack_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":9,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.18,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":70,
                            "power":40,
                            "kbConstant":80,
                            "effectSound":"ssf2_snd_sfx_simon_attack_hit_m"
                        },
                        "attackBox2":{
                            "damage":9,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.18,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":70,
                            "power":40,
                            "kbConstant":80,
                            "effectSound":"ssf2_snd_sfx_simon_attack_hit_m"
                        },
                        "attackBox3":{
                            "damage":9,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.18,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":70,
                            "power":40,
                            "kbConstant":80,
                            "effectSound":"ssf2_snd_sfx_simon_attack_hit_m"
                        }
                    }
                },
                "a_air_up":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"ssf2_snd_vfx_simon_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_simon_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_simon_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_simon_attack04",
                    "attackSound1_id":"ssf2_snd_sfx_simon_attack_swing_s",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":7,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":90,
                            "power":50,
                            "kbConstant":90,
                            "effectSound":"ssf2_snd_sfx_simon_attack_hit_m"
                        },
                        "attackBox2":{
                            "damage":7,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":90,
                            "power":50,
                            "kbConstant":90,
                            "effectSound":"ssf2_snd_sfx_simon_attack_hit_m"
                        },
                        "attackBox3":{
                            "damage":10,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":90,
                            "power":50,
                            "kbConstant":90,
                            "effectSound":"ssf2_snd_sfx_simon_attack_hit_m"
                        }
                    }
                },
                "a_air_forward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"ssf2_snd_vfx_simon_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_simon_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_simon_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_simon_attack04",
                    "attackSound1_id":"ssf2_snd_sfx_simon_attack_swing_s",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":7,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":0,
                            "power":40,
                            "kbConstant":85,
                            "effectSound":"ssf2_snd_sfx_simon_attack_hit_s"
                        },
                        "attackBox2":{
                            "damage":7,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":0,
                            "power":40,
                            "kbConstant":85,
                            "effectSound":"ssf2_snd_sfx_simon_attack_hit_s"
                        },
                        "attackBox3":{
                            "damage":10,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":0,
                            "power":40,
                            "kbConstant":85,
                            "effectSound":"ssf2_snd_sfx_simon_attack_hit_m"
                        }
                    }
                },
                "a_air_backward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"ssf2_snd_vfx_simon_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_simon_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_simon_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_simon_attack04",
                    "attackSound1_id":"ssf2_snd_sfx_simon_attack_swing_s",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":7,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":0,
                            "power":40,
                            "kbConstant":100,
                            "effectSound":"ssf2_snd_sfx_simon_attack_hit_s"
                        },
                        "attackBox2":{
                            "damage":7,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":0,
                            "power":40,
                            "kbConstant":100,
                            "effectSound":"ssf2_snd_sfx_simon_attack_hit_s"
                        },
                        "attackBox3":{
                            "damage":10,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":0,
                            "power":40,
                            "kbConstant":100,
                            "effectSound":"ssf2_snd_sfx_simon_attack_hit_m"
                        }
                    }
                },
                "a_air_down":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"ssf2_snd_vfx_simon_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_simon_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_simon_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_simon_attack04",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "hitStun":5,
                            "hitLag":-1.1,
                            "selfHitStun":3,
                            "effect_id":"effect_heavyHit",
                            "direction":290,
                            "power":60,
                            "kbConstant":60,
                            "effectSound":null
                        }}
                },
                "b":{
                    "refreshRate":2,
                    "canFallOff":false,
                    "allowControl":false,
                    "cancelWhenAirborne":false,
                    "allowFastFall":false,
                    "attackVoice1_id":"ssf2_snd_vfx_simon_nspec",
                    "attackSound1_id":"ssf2_snd_sfx_simon_nspec",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":1,
                            "hitStun":2,
                            "selfHitStun":0,
                            "direction":75,
                            "power":20,
                            "kbConstant":50,
                            "effectSound":"sw_brawl_hit_S",
                            "effect_id":"effect_swordSlash"
                        }}
                },
                "b_air":{
                    "refreshRate":2,
                    "allowControl":false,
                    "cancelWhenAirborne":false,
                    "allowFastFall":false,
                    "attackVoice1_id":"ssf2_snd_vfx_simon_nspec",
                    "attackSound1_id":"ssf2_snd_sfx_simon_nspec",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":1,
                            "hitStun":2,
                            "selfHitStun":0,
                            "direction":75,
                            "power":20,
                            "kbConstant":50,
                            "effectSound":"sw_brawl_hit_S",
                            "effect_id":"effect_swordSlash"
                        }}
                },
                "b_up":{
                    "disableForCPU":true,
                    "xSpeedDecay":-0.65,
                    "allowFastFall":false,
                    "canFallOff":true,
                    "cancelWhenAirborne":false,
                    "canGrabInverseLedges":false,
                    "attackSound1_id":"ssf2_snd_sfx_simon_attack_swing_s",
                    "attackSound2_id":"ssf2_snd_sfx_simon_attack_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":3,
                            "direction":60,
                            "power":60,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m",
                            "effect_id":"effect_hit2",
                            "reversableAngle":false
                        }}
                },
                "b_up_air":{
                    "disableForCPU":false,
                    "xSpeedDecay":-0.65,
                    "allowFastFall":false,
                    "cancelWhenAirborne":false,
                    "isHorizontalRecoveryMove":false,
                    "isRecoveryMove":true,
                    "attackSound1_id":"ssf2_snd_sfx_simon_attack_swing_s",
                    "attackSound2_id":"ssf2_snd_sfx_simon_attack_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":6,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":3,
                            "direction":60,
                            "power":60,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m",
                            "effect_id":"effect_hit2",
                            "reversableAngle":false
                        },
                        "attackBox2":{
                            "damage":6,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":3,
                            "direction":60,
                            "power":60,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m",
                            "effect_id":"effect_hit2",
                            "reversableAngle":false
                        }
                    }
                },
                "b_forward":{
                    "isLongRangeMove":true,
                    "canFallOff":false,
                    "attackVoice1_id":"ssf2_snd_vfx_simon_fspec",
                    "attackSound1_id":"ssf2_snd_sfx_simon_fspec_throw",
                    "attackBoxes":{"attackBox":{
                            "damage":15,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":2,
                            "direction":45,
                            "power":64,
                            "kbConstant":96,
                            "effectSound":"brawl_punch_m",
                            "effect_id":"effect_aurahit_light"
                        }}
                },
                "b_forward_air":{
                    "isLongRangeMove":true,
                    "allowControl":true,
                    "canFallOff":false,
                    "attackVoice1_id":"ssf2_snd_vfx_simon_fspec",
                    "attackSound1_id":"ssf2_snd_sfx_simon_fspec_throw",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":2,
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "b_down":{
                    "canFallOff":false,
                    "cancelWhenAirborne":false,
                    "attackSound1_id":"ssf2_snd_sfx_simon_dspec_throw",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":0,
                            "hitStun":7,
                            "hitLag":-0.6,
                            "selfHitStun":7,
                            "effect_id":"effect_elechit_heavy",
                            "direction":75,
                            "power":40,
                            "kbConstant":105,
                            "effectSound":"lucario_hit_dspec"
                        }}
                },
                "b_down_air":{
                    "allowControl":true,
                    "attackSound1_id":"ssf2_snd_sfx_simon_dspec_throw",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":0,
                            "hitStun":7,
                            "hitLag":-0.6,
                            "selfHitStun":7,
                            "effect_id":"effect_elechit_heavy",
                            "direction":75,
                            "power":40,
                            "kbConstant":105,
                            "effectSound":"lucario_hit_dspec"
                        }}
                },
                "throw_up":{
                    "canFallOff":false,
                    "attackVoice1_id":"ssf2_snd_vfx_simon_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_simon_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_simon_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_simon_attack04",
                    "attackSound1_id":"throw_woosh",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":0,
                            "hitStun":6,
                            "selfHitStun":3,
                            "hitLag":-1.1,
                            "effect_id":"effect_hit3",
                            "direction":90,
                            "power":58,
                            "kbConstant":55,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "throw_forward":{
                    "canFallOff":false,
                    "attackVoice1_id":"ssf2_snd_vfx_simon_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_simon_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_simon_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_simon_attack04",
                    "attackSound1_id":"throw_woosh",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":null,
                            "direction":40,
                            "reversableAngle":false,
                            "power":70,
                            "kbConstant":40,
                            "bypassNonGrabbed":true,
                            "effectSound":"melee_throw"
                        }}
                },
                "throw_back":{
                    "canFallOff":false,
                    "attackVoice1_id":"ssf2_snd_vfx_simon_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_simon_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_simon_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_simon_attack04",
                    "attackSound1_id":"throw_woosh",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":0,
                            "hitStun":8,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":110,
                            "reversableAngle":false,
                            "power":58,
                            "kbConstant":74,
                            "bypassNonGrabbed":false,
                            "forceTumbleFall":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "throw_down":{
                    "canFallOff":false,
                    "attackVoice1_id":"ssf2_snd_vfx_simon_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_simon_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_simon_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_simon_attack04",
                    "attackSound1_id":"throw_woosh",
                    "attackBoxes":{"attackBox":{
                            "damage":15,
                            "priority":0,
                            "hitStun":5,
                            "selfHitStun":3,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "reversableAngle":false,
                            "power":94,
                            "kbConstant":32,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "crouch_attack":{
                    "canFallOff":false,
                    "attackVoice1_id":"ssf2_snd_vfx_simon_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_simon_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_simon_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_simon_attack04",
                    "attackSound1_id":"ssf2_snd_sfx_simon_attack_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":9,
                            "priority":2,
                            "hitStun":4,
                            "selfHitStun":3,
                            "effect_id":"effect_hit3",
                            "direction":270,
                            "power":120,
                            "kbConstant":35,
                            "onlyAffectsGround":true,
                            "effectSound":"ssf2_snd_sfx_simon_attack_hit_m"
                        },
                        "attackBox2":{
                            "damage":9,
                            "priority":2,
                            "hitStun":4,
                            "selfHitStun":3,
                            "effect_id":"effect_hit3",
                            "direction":10,
                            "power":45,
                            "kbConstant":48,
                            "onlyAffectsAir":true,
                            "effectSound":"ssf2_snd_sfx_simon_attack_hit_m"
                        },
                        "attackBox3":{
                            "damage":8,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":50,
                            "power":65,
                            "kbConstant":65,
                            "effectSound":"ssf2_snd_sfx_simon_attack_hit_m"
                        }
                    }
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackVoice1_id":"ssf2_snd_vfx_simon_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_simon_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_simon_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_simon_attack04",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "direction":45,
                            "power":75,
                            "kbConstant":25,
                            "effect_id":"effect_lightHit",
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "getup_attack":{
                    "attackSound1_id":"lucario_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":6,
                            "priority":0,
                            "hitStun":-1,
                            "selfHitStun":-1,
                            "direction":0,
                            "power":40,
                            "kbConstant":100,
                            "effect_id":"effect_hit3",
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":6,
                            "priority":0,
                            "hitStun":-1,
                            "selfHitStun":-1,
                            "direction":0,
                            "power":40,
                            "kbConstant":100,
                            "effect_id":"effect_hit3",
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "kirby":{
                    "refreshRate":1,
                    "air_ease":3,
                    "attackVoice1_id":"zelda_nspec",
                    "attackSound1_id":"zelda_nayru",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":2,
                            "hitStun":4,
                            "selfHitStun":0,
                            "direction":25,
                            "power":0,
                            "kbConstant":60,
                            "effectSound":"brawl_kick_s"
                        }}
                },
                "kirby_air":{
                    "refreshRate":1,
                    "air_ease":3,
                    "isHorizontalRecoveryMove":true,
                    "attackVoice1_id":"zelda_nspec",
                    "attackSound1_id":"zelda_nayru",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":2,
                            "hitStun":4,
                            "selfHitStun":0,
                            "direction":25,
                            "power":0,
                            "kbConstant":60,
                            "effectSound":"brawl_kick_s"
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "invincible":true,
                    "air_ease":0,
                    "canUseInAir":true
                },
                "item_jab":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_tilt":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_dash":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_smash":{
                    "chargetime_max":40,
                    "chargeClick":true,
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false,
                    "attackVoice1_id":"ssf2_snd_vfx_simon_fsmash"
                },
                "item_homerun":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false,
                    "attackVoice1_id":"ssf2_snd_vfx_simon_attack02"
                },
                "item_fan":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_shoot":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "canFallOff":false
                },
                "item_heavyshoot":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "canFallOff":false
                },
                "item_raise":{
                    "maintainSpeed":false,
                    "canFallOff":false
                },
                "item_screw":{
                    "refreshRate":1,
                    "allowControl":true,
                    "air_ease":0,
                    "maintainSpeed":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "attackBoxes":{
                        "attackBox":{
                            "damage":1,
                            "priority":5,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":95,
                            "power":125,
                            "kbConstant":10,
                            "stackKnockback":false,
                            "shock":true,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox2":{
                            "damage":1,
                            "priority":5,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":95,
                            "power":125,
                            "kbConstant":10,
                            "stackKnockback":false,
                            "shock":true,
                            "effectSound":"brawl_kick_s"
                        }
                    }
                },
                "item_firedash":{
                    "allowControl":false,
                    "air_ease":0,
                    "maintainSpeed":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "effect_id":"effect_firehit_heavy",
                            "direction":45,
                            "power":25,
                            "kbConstant":110,
                            "burn":true,
                            "effectSound":"brawl_fire_l"
                        }}
                },
                "item_bubblebounce":{
                    "allowControl":true,
                    "air_ease":-1,
                    "maintainSpeed":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "xSpeedCap":6,
                    "xSpeedAccel":0.75,
                    "xSpeedAccelAir":0.75,
                    "xSpeedDecay":0.99,
                    "xSpeedDecayAir":0.99,
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "effect_id":"effect_waterhit_heavy",
                            "direction":270,
                            "power":20,
                            "kbConstant":80,
                            "effectSound":"sfx_waterhit_m"
                        }}
                }
            };
            var _local_3:Object = {
                "batSwingRing":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"batSwingRing",
                    "time_max":30,
                    "xspeed":0,
                    "yspeed":0,
                    "maxgravity":0,
                    "limit":1,
                    "limitOverwrite":true,
                    "inheritPalette":true,
                    "canBePocketed":false,
                    "canBeReversed":false,
                    "ghost":true,
                    "dangerous":false,
                    "attack_idle":{}
                },
                "cross_boomerang":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"cross_boomerang",
                    "height":20,
                    "width":20,
                    "time_max":0,
                    "rideGround":false,
                    "boomerang":false,
                    "xspeed":26,
                    "canBeReversed":true,
                    "canBeAbsorbed":false,
                    "limit":1,
                    "limitOverwrite":false,
                    "inheritPalette":true,
                    "attack_idle":{
                        "refreshRate":420,
                        "attackBoxes":{"attackBox":{
                                "damage":5,
                                "priority":7,
                                "effect_id":"effect_heavyHit",
                                "direction":60,
                                "power":55,
                                "kbConstant":60,
                                "reversableAngle":false,
                                "effectSound":"brawl_punch_m"
                            }}
                    }
                },
                "axe":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"axe",
                    "height":36,
                    "width":36,
                    "time_max":0,
                    "xspeed":9,
                    "yspeed":-23,
                    "gravity":2.5,
                    "maxgravity":16,
                    "canBeReversed":true,
                    "limit":1,
                    "limitOverwrite":false,
                    "canBeAbsorbed":false,
                    "inheritPalette":true,
                    "attack_idle":{
                        "refreshRate":420,
                        "attackBoxes":{"attackBox":{
                                "damage":16,
                                "hitStun":6,
                                "hitLag":-1,
                                "selfHitStun":6,
                                "effect_id":"effect_swordSlash",
                                "direction":50,
                                "power":60,
                                "kbConstant":90,
                                "effectSound":"sw_brawl_hit_H"
                            }}
                    }
                },
                "water":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"water",
                    "height":36,
                    "width":36,
                    "time_max":0,
                    "limit":1,
                    "limitOverwrite":false,
                    "xspeed":6,
                    "yspeed":15,
                    "gravity":0,
                    "maxgravity":16,
                    "canBeReversed":true,
                    "canBeAbsorbed":false,
                    "attack_idle":{
                        "refreshRate":15,
                        "attackBoxes":{"attackBox":{
                                "damage":4,
                                "hitStun":3,
                                "hitLag":-1,
                                "selfHitStun":1,
                                "effect_id":"effect_aurahit_light",
                                "direction":80,
                                "power":50,
                                "kbConstant":70,
                                "effectSound":"brawl_fire_s",
                                "aura":true
                            }}
                    }
                },
                "jab_whip":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"jab_whip",
                    "height":0,
                    "width":0,
                    "inheritPalette":true,
                    "time_max":99999999999,
                    "limit":1,
                    "gravity":0,
                    "maxgravity":0,
                    "canBePocketed":false,
                    "inheritPalette":true,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "ghost":true,
                    "attack_idle":{
                        "refreshRate":8,
                        "attackBoxes":{"attackBox":{
                                "damage":3,
                                "hitStun":3,
                                "hitLag":-1.2,
                                "sdiDistance":2,
                                "priority":-1,
                                "selfHitStun":0,
                                "effect_id":"effect_hit3",
                                "direction":40,
                                "power":20,
                                "kbConstant":90,
                                "effectSound":"ssf2_snd_sfx_simon_attack_hit_s"
                            }}
                    }
                },
                "simon_coffin":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"simon_coffin_proj",
                    "width":27,
                    "height":38,
                    "time_max":60,
                    "xspeed":0,
                    "xdecay":-0.2,
                    "canBePocketed":false,
                    "canBeReversed":false,
                    "inheritPalette":true,
                    "canBeAbsorbed":false,
                    "rotate":false,
                    "xoffset":150,
                    "yoffset":-50,
                    "attack_idle":{
                        "refreshRate":1000,
                        "attackBoxes":{"attackBox":{
                                "damage":5,
                                "hasEffect":false,
                                "bypassShield":true,
                                "bypassGrabbed":true,
                                "burn":true,
                                "priority":-1,
                                "hitStun":2,
                                "selfHitStun":1,
                                "kbConstant":20,
                                "effectSound":"brawl_punch_l"
                            }}
                    }
                }
            };
            var _local_4:Object;
            return {
                "cData":_local_1,
                "aData":_local_2,
                "pData":_local_3,
                "iData":_local_4
            };
        }


    }
}

