package
{
    public dynamic class Main extends SSF2Asset
    {

        public var number_9:gaw_9effect;

        public function Main()
        {
            super();
            register("id", "gameandwatch");
            register("guid", "65319743-bb44-4f70-87ce-cee7a2551a18");
            register("characters", [this.getgameandwatch()]);
            register("resources", {
                "movieclips":["oil_panic", "bacon", "gaw_9effect", "link_dust_cloud", "link_globalSpark", "link_dust_light", "link_dust_swirl", "gameandwatch", "gaw_firemen", "gameandwatch_icon", "gameandwatch_head"],
                "sounds":["beep5", "beep_1", "beep_2", "beep_3", "beep_4", "beep_crouch_1", "beep_crouch_2", "beep_dair_landing", "beep_fsmash", "beep_high", "beep_jump", "beep_jump_midair", "beep_lose", "beep_low", "beep_low_mid", "beep_mid", "beep_mid_high", "beep_nair", "beep_skid", "beep_step_1", "beep_step_2", "freeze_hit", "gw_aerial1", "gw_aerial2", "gw_dashattack01", "gw_dashattack02", "gw_dtilt", "gw_ftilt01", "gw_ftilt02", "gw_jabpull", "gw_jabpush", "gw_nairend", "gw_usmash", "ring", "gw_taunt", "gw_entrance1", "gw_entrance2", "gw_entrance3", "gw_entrance4", "gw_dash", "gw_dash_stop", "snd_se_GW_Escape", "gw_step2", "gw_step1", "snd_se_GW_EscapeAir", "snd_se_GW_Final01", "snd_se_GW_Final02", "snd_se_GW_Final03", "snd_se_GW_Final04", "snd_se_GW_Fire", "snd_se_GW_Flag", "snd_se_GW_Hammer", "gw_jump1", "gw_jump2", "gw_shorthop", "snd_se_GW_Landing02", "snd_se_GW_Manhole", "snd_se_GW_Parachute", "snd_se_GW_rise", "snd_se_GW_Smash_S01", "snd_se_GW_Smash_Start", "snd_se_GW_Special_C2_L01", "snd_se_GW_Special_C3_H01", "snd_se_GW_Special_C3_L01", "snd_se_GW_Special_L01", "snd_se_GW_Special_S01", "snd_se_GW_SpitBall", "snd_se_GW_squat", "snd_se_GW_step_hidari_m", "snd_se_GW_step_hidari_s", "snd_se_GW_step_migi_m", "snd_se_GW_step_migi_s", "snd_se_GW_swing_s", "snd_se_GW_Wave01_Hi", "snd_se_GW_Wave01_Lo", "snd_se_GW_Wave01_Mi", "snd_se_GW_Wave02_Hi", "snd_se_GW_Wave02_Lo", "snd_se_GW_Wave02_Mi", "snd_se_GW_Wave03_Hi", "snd_se_GW_Wave03_Lo", "snd_se_GW_Wave03_Mi", "snd_se_GW_Wave04_Hi", "snd_se_GW_Wave04_Lo", "snd_se_GW_Wave04_Mi", "snd_se_GW_Wave05_Hi", "snd_se_GW_Wave05_Lo", "snd_se_GW_Wave05_Mi", "snd_se_GW_Wave06_Hi", "snd_se_GW_Wave06_Lo", "snd_se_GW_Wave06_Mi", "snd_se_GW_Wave07_Hi", "snd_se_GW_Wave07_Lo", "snd_se_GW_Wave07_Mi", "snd_se_GW_Wave08_Hi", "snd_se_GW_Wave08_Lo", "snd_se_GW_Wave08_Mi", "snd_se_GW_Wave09_Hi", "snd_se_GW_Wave09_Lo", "snd_se_GW_Wave09_Mi", "snd_se_GW_Wave10_Hi", "snd_se_GW_Wave10_Hi_Special_C2_H01", "snd_se_GW_Wave10_Lo", "snd_se_GW_Wave10_Mi", "snd_se_GW_Wave10_Mi_Special_C2_H01", "snd_se_GW_Win_01", "snd_se_GW_Win_02", "snd_se_GW_Win_03", "snd_se_GW_Win_04", "gameandwatch_starko"]
            });
        }

        public function getgameandwatch():Object
        {
            var _local_1:Object = new Object();
            _local_1 = {
                "statsName":"gameandwatch",
                "displayName":"Mr. Game & Watch boi ya lol",
                "classAPI":gameandwatchExt,
                "linkage_id":"gameandwatch",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"gameandwatch_head",
                "seriesIcon":"gameandwatch_icon",
                "width":38,
                "height":48,
                "maxShieldSize":1.3,
                "jumpSpeed":17,
                "jumpSpeedMidair":16,
                "jumpStartup":3,
                "shortHopSpeed":10.5,
                "max_jumpSpeed":8.1,
                "groundToAirMultiplier":0.817,
                "dodgeSpeed":16,
                "dodgeDecel":-1.3,
                "gravity":1.3,
                "weight1":76,
                "power":"gameAndWatch",
                "norm_xSpeed":4.1,
                "max_xSpeed":10.4,
                "max_ySpeed":9.2,
                "fastFallSpeed":15.1,
                "accel_start":0.49,
                "accel_start_dash":1.1,
                "accel_rate":1,
                "accel_rate_air":0.75,
                "decel_rate":-1.3,
                "decel_rate_air":-0.15,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":100,
                "tetherGrab":false,
                "roll_speed":28,
                "roll_decay":0.74,
                "getup_roll_delay":2,
                "tech_roll_delay":3,
                "climb_roll_delay":8,
                "itemScaleRatio":1,
                "special_type":1,
                "finalSmashCutin":"gnw_fs_cutin",
                "normalStats_id":"gameandwatch",
                "specialStats_id":null,
                "sounds":{
                    "jump":null,
                    "jump_midair":null,
                    "hurt":null,
                    "hurt2":null,
                    "hurtBad":null,
                    "hurtBad2":null,
                    "dead":null,
                    "dead2":null,
                    "pummel":"brawl_punch_s",
                    "screenko":null,
                    "starko":"gameandwatch_starko",
                    "ledge_grab":null,
                    "winTheme":"gw_win"
                },
                "hurtFrames":3,
                "grabDamage":3
            };
            var _local_2:Object = new Object();
            _local_2 = {
                "a":{
                    "canFallOff":false,
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":1,
                            "effect_id":"effect_hit1",
                            "direction":83,
                            "power":0,
                            "kbConstant":100,
                            "weightKB":20,
                            "effectSound":"brawl_fire_m",
                            "hitLag":-1.3
                        }}
                },
                "a_up":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackBoxes":{
                        "attackBox":{
                            "damage":16,
                            "priority":6,
                            "chargedPriority":6,
                            "effect_id":"effect_heavyHit",
                            "direction":83,
                            "power":40,
                            "kbConstant":93,
                            "effectSound":"whack"
                        },
                        "attackBox2":{
                            "damage":16,
                            "priority":6,
                            "chargedPriority":6,
                            "effect_id":"effect_heavyHit",
                            "direction":83,
                            "power":40,
                            "kbConstant":93,
                            "effectSound":"whack"
                        }
                    }
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "attackBoxes":{
                        "attackBox":{
                            "damage":7,
                            "priority":3,
                            "effect_id":"effect_lightHit",
                            "hitStun":4,
                            "selfHitStun":1,
                            "direction":95,
                            "power":40,
                            "kbConstant":105,
                            "effectSound":"brawl_kick_m",
                            "hitLag":-1.2
                        },
                        "attackBox2":{
                            "damage":7,
                            "priority":3,
                            "effect_id":"effect_lightHit",
                            "hitStun":4,
                            "selfHitStun":1,
                            "direction":95,
                            "power":40,
                            "kbConstant":105,
                            "effectSound":"brawl_kick_m",
                            "hitLag":-1.2
                        }
                    }
                },
                "a_forward":{
                    "canFallOff":false,
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":2,
                            "effect_id":"effect_lightHit",
                            "direction":45,
                            "power":60,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "attackBoxes":{
                        "attackBox":{
                            "damage":10,
                            "priority":2,
                            "effect_id":"effect_lightHit",
                            "direction":30,
                            "power":50,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":9,
                            "priority":2,
                            "effect_id":"effect_lightHit",
                            "direction":45,
                            "power":35,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackBoxes":{
                        "attackBox":{
                            "burn":true,
                            "damage":14,
                            "priority":5,
                            "direction":48,
                            "power":40,
                            "kbConstant":80,
                            "effect_id":"effect_firehit_heavy",
                            "effectSound":"brawl_fire_l"
                        },
                        "attackBox2":{
                            "burn":true,
                            "damage":18,
                            "priority":5,
                            "direction":48,
                            "power":48,
                            "kbConstant":91,
                            "effect_id":"effect_firehit_heavy",
                            "effectSound":"brawl_fire_l"
                        }
                    }
                },
                "a_down":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackBoxes":{
                        "attackBox":{
                            "damage":13,
                            "priority":4,
                            "chargedPriority":5,
                            "effect_id":"effect_heavyHit",
                            "direction":20,
                            "power":30,
                            "kbConstant":65,
                            "effectSound":"brawl_punch_l"
                        },
                        "attackBox2":{
                            "damage":15,
                            "priority":5,
                            "chargedPriority":6,
                            "effect_id":"effect_heavyHit",
                            "direction":75,
                            "power":60,
                            "kbConstant":85,
                            "effectSound":"brawl_punch_l"
                        },
                        "attackBox3":{
                            "damage":15,
                            "priority":5,
                            "chargedPriority":6,
                            "effect_id":"effect_heavyHit",
                            "direction":75,
                            "power":60,
                            "kbConstant":85,
                            "effectSound":"brawl_punch_l"
                        }
                    }
                },
                "a_air":{
                    "allowControl":true,
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "priority":3,
                            "hitStun":1,
                            "hitLag":5,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":90,
                            "power":0,
                            "kbConstant":0,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox2":{
                            "damage":3,
                            "priority":3,
                            "hitStun":1,
                            "hitLag":5,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":90,
                            "power":0,
                            "kbConstant":0,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox3":{
                            "damage":3,
                            "priority":3,
                            "hitStun":1,
                            "hitLag":5,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":90,
                            "power":0,
                            "kbConstant":0,
                            "effectSound":"brawl_kick_s"
                        }
                    }
                },
                "a_air_up":{
                    "allowControl":true,
                    "attackBoxes":{
                        "attackBox":{
                            "damage":7,
                            "priority":2,
                            "effect_id":"effect_heavyHit",
                            "direction":94,
                            "power":55,
                            "kbConstant":0,
                            "effectSound":"brawl_fire_m",
                            "hitLag":-1.15
                        },
                        "attackBox2":{
                            "stackKnockback":true,
                            "hasEffect":false,
                            "damage":0,
                            "priority":-1,
                            "hitStun":0,
                            "selfHitStun":0,
                            "direction":90,
                            "power":60,
                            "kbConstant":130
                        },
                        "attackBox3":{
                            "stackKnockback":true,
                            "hasEffect":false,
                            "damage":0,
                            "priority":-1,
                            "hitStun":0,
                            "selfHitStun":0,
                            "direction":90,
                            "power":40,
                            "kbConstant":130
                        }
                    }
                },
                "a_air_forward":{
                    "allowControl":true,
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitLag":-1.15,
                            "effect_id":"effect_heavyHit",
                            "direction":40,
                            "power":55,
                            "kbConstant":85,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_air_backward":{
                    "allowControl":true,
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":4,
                            "hitLag":-1.15,
                            "hitStun":5,
                            "selfHitStun":3,
                            "effect_id":"effect_swordSlash",
                            "direction":25,
                            "power":20,
                            "kbConstant":40,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "a_air_down":{
                    "air_ease":0,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "allowFastFall":false,
                    "allowControlGround":false,
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":4,
                            "effect_id":"effect_heavyHit",
                            "direction":270,
                            "power":50,
                            "kbConstant":70,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "b":{
                    "isLongRangeMove":true,
                    "cancelWhenAirborne":false,
                    "allowControlGround":false,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "attackBoxes":{"attackBox":{
                            "burn":true,
                            "damage":5,
                            "priority":2,
                            "direction":10,
                            "power":60,
                            "kbConstant":30,
                            "effect_id":"effect_firehit_light",
                            "effectSound":"brawl_fire_s"
                        }}
                },
                "b_air":{
                    "isLongRangeMove":true,
                    "allowControlGround":false,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "attackBoxes":{"attackBox":{
                            "burn":true,
                            "damage":5,
                            "priority":2,
                            "direction":10,
                            "power":60,
                            "kbConstant":30,
                            "effect_id":"effect_firehit_light",
                            "effectSound":"brawl_fire_s"
                        }}
                },
                "b_up":{
                    "xSpeedDecayAir":1,
                    "xSpeedAccelAir":1,
                    "xSpeedCap":9,
                    "isRecoveryMove":true,
                    "cancelWhenAirborne":false,
                    "allowRun":false,
                    "allowControl":false,
                    "air_ease":3.5,
                    "allowFastFall":false,
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":2,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "power":135,
                            "kbConstant":0,
                            "effectSound":"brawl_kick_m",
                            "stackKnockback":false,
                            "canDI":false
                        }}
                },
                "b_up_air":{
                    "xSpeedDecayAir":1,
                    "xSpeedAccelAir":1,
                    "xSpeedCap":9,
                    "isRecoveryMove":true,
                    "cancelWhenAirborne":false,
                    "allowControl":false,
                    "allowRun":false,
                    "air_ease":3.5,
                    "allowFastFall":false,
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":2,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "power":135,
                            "kbConstant":0,
                            "effectSound":"brawl_kick_m",
                            "stackKnockback":false,
                            "canDI":false
                        }}
                },
                "b_forward":{
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":1,
                            "effect_id":"effect_hit3",
                            "direction":35,
                            "power":0,
                            "kbConstant":0,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "b_forward_air":{
                    "cancelWhenAirborne":false,
                    "xSpeedDecayAir":-0.4,
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":1,
                            "effect_id":"effect_hit3",
                            "direction":35,
                            "power":0,
                            "kbConstant":0,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "b_down":{
                    "resetMovement":false,
                    "cancelWhenAirborne":false,
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":7,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":65,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "b_down_air":{
                    "resetMovement":false,
                    "cancelWhenAirborne":false,
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":7,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":65,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "throw_up":{
                    "canFallOff":false,
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":0,
                            "direction":85,
                            "reversableAngle":false,
                            "power":90,
                            "kbConstant":35,
                            "bypassNonGrabbed":true,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effectSound":"melee_throw"
                        }}
                },
                "throw_forward":{
                    "canFallOff":false,
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":0,
                            "direction":58,
                            "reversableAngle":false,
                            "power":80,
                            "kbConstant":30,
                            "bypassNonGrabbed":true,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effectSound":"melee_throw"
                        }}
                },
                "throw_back":{
                    "canFallOff":false,
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":0,
                            "direction":122,
                            "reversableAngle":false,
                            "power":110,
                            "kbConstant":45,
                            "bypassNonGrabbed":true,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effectSound":"melee_throw"
                        }}
                },
                "throw_down":{
                    "canFallOff":false,
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":0,
                            "hitLag":-0.15,
                            "direction":270,
                            "reversableAngle":false,
                            "meteorBounce":false,
                            "forceTumbleFall":true,
                            "power":35,
                            "kbConstant":115,
                            "bypassNonGrabbed":true,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effectSound":"melee_throw"
                        }}
                },
                "crouch_attack":{
                    "canFallOff":false,
                    "attackBoxes":{
                        "attackBox":{
                            "damage":10,
                            "priority":3,
                            "hitLag":-1.2,
                            "effect_id":"effect_lightHit",
                            "direction":75,
                            "power":58,
                            "kbConstant":55,
                            "effectSound":"brawl_punch_m"
                        },
                        "attackBox2":{
                            "damage":0,
                            "direction":90,
                            "power":110,
                            "kbConstant":0,
                            "hasEffect":false,
                            "onlyAffectsAir":true
                        }
                    }
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "direction":45,
                            "power":75,
                            "kbConstant":25,
                            "effect_id":"effect_hit2",
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "getup_attack":{
                    "canFallOff":false,
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":2,
                            "effect_id":"effect_hit1",
                            "direction":45,
                            "power":80,
                            "kbConstant":40,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "kirby":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "canFallOff":false,
                    "chargeInAir":false,
                    "canUseInAir":true,
                    "attackVoice1_id":"Kirby_Attack01",
                    "attackSound1_id":"tails_bshot",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":2,
                            "hitLag":0.45,
                            "direction":10,
                            "power":-1000,
                            "kbConstant":16,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "kirby_air":{
                    "refreshRate":1000,
                    "allowControl":true,
                    "chargeInAir":false,
                    "canUseInAir":true,
                    "reenableTimer":3000,
                    "attackVoice1_id":"Kirby_Attack01",
                    "attackSound1_id":"tails_bshot",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":2,
                            "hitLag":0.45,
                            "direction":10,
                            "power":-1000,
                            "kbConstant":16,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "taunt":{
                    "canFallOff":true,
                    "attackBoxes":{"attackBox":{
                            "stackKnockback":true,
                            "hasEffect":false,
                            "reversableAngle":false,
                            "damage":0,
                            "priority":-1,
                            "hitStun":0,
                            "selfHitStun":0,
                            "direction":0,
                            "power":25,
                            "kbConstant":130
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "air_ease":0,
                    "refreshRate":30,
                    "allowControl":true,
                    "xSpeedCap":5,
                    "xSpeedAccel":0.75,
                    "cancelWhenAirborne":false,
                    "canUseInAir":true,
                    "attackBoxes":{
                        "attackBox":{
                            "damage":16,
                            "priority":0,
                            "selfHitStun":1,
                            "direction":45,
                            "power":50,
                            "kbConstant":80,
                            "bypassShield":true,
                            "bypassHeavyArmor":true,
                            "bypassSuperArmor":true,
                            "effect_id":"effect_lightHit",
                            "effectSound":"brawl_punch_l"
                        },
                        "attackBox2":{
                            "damage":16,
                            "priority":0,
                            "selfHitStun":1,
                            "direction":45,
                            "power":50,
                            "kbConstant":100,
                            "bypassShield":true,
                            "bypassHeavyArmor":true,
                            "bypassSuperArmor":true,
                            "effect_id":"effect_lightHit",
                            "effectSound":"brawl_punch_l"
                        },
                        "attackBox3":{
                            "damage":16,
                            "priority":0,
                            "selfHitStun":1,
                            "direction":45,
                            "power":50,
                            "kbConstant":100,
                            "bypassShield":true,
                            "bypassHeavyArmor":true,
                            "bypassSuperArmor":true,
                            "effect_id":"effect_lightHit",
                            "effectSound":"brawl_punch_l"
                        },
                        "attackBox4":{
                            "damage":16,
                            "priority":0,
                            "selfHitStun":1,
                            "direction":45,
                            "power":50,
                            "kbConstant":100,
                            "bypassShield":true,
                            "bypassHeavyArmor":true,
                            "bypassSuperArmor":true,
                            "effect_id":"effect_lightHit",
                            "effectSound":"brawl_punch_l"
                        }
                    }
                },
                "item_jab":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_tilt":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_dash":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_smash":{
                    "chargetime_max":40,
                    "chargeClick":true,
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_homerun":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_fan":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_shoot":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "canFallOff":false
                },
                "item_heavyshoot":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "canFallOff":false
                },
                "item_raise":{
                    "maintainSpeed":false,
                    "canFallOff":false
                },
                "item_float":{
                    "maintainSpeed":true,
                    "canFallOff":true
                },
                "item_screw":{
                    "refreshRate":1,
                    "allowControl":true,
                    "air_ease":0,
                    "maintainSpeed":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "attackBoxes":{
                        "attackBox":{
                            "damage":1,
                            "priority":5,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":95,
                            "power":125,
                            "kbConstant":10,
                            "stackKnockback":false,
                            "shock":true,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox2":{
                            "damage":1,
                            "priority":5,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":95,
                            "power":125,
                            "kbConstant":10,
                            "stackKnockback":false,
                            "shock":true,
                            "effectSound":"brawl_kick_s"
                        }
                    }
                },
                "item_firedash":{
                    "allowControl":false,
                    "air_ease":0,
                    "maintainSpeed":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "effect_id":"effect_firehit_heavy",
                            "direction":45,
                            "power":25,
                            "kbConstant":110,
                            "burn":true,
                            "effectSound":"brawl_fire_l"
                        }}
                },
                "item_bubblebounce":{
                    "allowControl":true,
                    "air_ease":-1,
                    "maintainSpeed":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "xSpeedCap":6,
                    "xSpeedAccel":0.75,
                    "xSpeedAccelAir":0.75,
                    "xSpeedDecay":0.99,
                    "xSpeedDecayAir":0.99,
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "effect_id":"effect_waterhit_heavy",
                            "direction":270,
                            "power":20,
                            "kbConstant":80,
                            "effectSound":"sfx_waterhit_m"
                        }}
                }
            };
            var _local_3:Object = {
                "bacon":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"bacon",
                    "width":10,
                    "height":10,
                    "inheritPalette":true,
                    "time_max":-1,
                    "gravity":0.65,
                    "maxgravity":7,
                    "canBeAbsorbed":false,
                    "limit":5,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":5,
                                "priority":1,
                                "hitStun":2,
                                "direction":90,
                                "effect_id":"effect_lightHit",
                                "power":20,
                                "kbConstant":35,
                                "hitLag":-1.1,
                                "effectSound":"brawl_punch_m"
                            }}}
                },
                "firemen":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"firemen",
                    "width":1,
                    "height":1,
                    "inheritPalette":true,
                    "time_max":-1,
                    "gravity":0,
                    "maxgravity":0,
                    "ghost":true,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "limit":1,
                    "attack_idle":{"attackBoxes":{}}
                }
            };
            var _local_4:Object = {"gnw_apple":{
                    "type":"consumable",
                    "classAPI":GameAndWatchApple,
                    "linkage_id":"gnw_apple",
                    "landSound":"itemland",
                    "width":30,
                    "height":30,
                    "spawnLimit":10,
                    "canPickup":true,
                    "gravity":1,
                    "max_gravity":10,
                    "canReceiveDamage":false,
                    "canReceiveKnockback":false,
                    "pushCharacters":false
                }};
            return {
                "cData":_local_1,
                "aData":_local_2,
                "pData":_local_3,
                "iData":_local_4
            };
        }


    }
}

