package
{
    public dynamic class Main extends SSF2Asset
    {

        public function Main()
        {
            super();
            register("id", "captainfalcon");
            register("guid", "addc9f5b-48d8-49df-9b23-e53d64c0c65e");
            register("characters", [this.getCaptainFalcon()]);
            register("resources", {
                "movieclips":["AudioMC", "bleach_symbol1", "falcon_hud", "captainfalcon_dspec_proj", "captainfalcon_dspecair_proj", "captainfalcon_nspec_proj", "trail_cfalcon_bair", "trail_cfalcon_dair", "trail_cfalcon_dsmash", "trail_cfalcon_dtilt", "trail_cfalcon_fsmash", "trail_cfalcon_ftilt", "trail_cfalcon_jab1", "trail_cfalcon_jab2", "trail_cfalcon_jab3", "trail_cfalcon_nair", "trail_cfalcon_rjab", "trail_cfalcon_uair", "trail_cfalcon_usmash", "trail_cfalcon_utilt", "falcon_revival", "wind_wave", "falconAfterEffect", "fzero", "falcon", "captainfalcon_head", "explodecircle", "raptorboost_aerial_hit", "raptorboost_effect", "raptorboost_effect_trail", "raptorboost_ground_hit", "cfalcon_fairsparkle", "uspecSparkle"],
                "sounds":["blueFalcon_pass", "falcon_death", "falcon_death2", "falcon_toorar", "falcon_kick", "falcon_dspecLand", "entranceClose", "entranceLeave", "entranceOpen", "blueFalcon_leaves", "falcon_finalSmash", "blueFalcon", "falcon_peturar", "cfalcon_grunt1", "cfalcon_grunt2", "cfalcon_grunt3", "cfalcon_grunt4", "falcon_hurt", "falcon_hurt2", "falcon_hurtBad", "falcon_hurtBad2", "cfalcon_jabcombo1", "cfalcon_jabcombo2", "cfalcon_jabcombo3", "falcon_jumpS1", "falcon_jumpS2", "falcon_jump", "cfalcon_kickwind", "falcon_", "pawnch", "raptorBoost1", "raptorBoost2", "cfalcon_run_start", "falconSleep", "cfalcon_smashstart", "falcon_footstep", "falcon_footstep2", "cfalcon_swing_l", "cfalcon_swing_ll", "cfalcon_swing_m", "cfalcon_swing_s", "falcon_taunt1", "falcon_taunt2", "cfalcon_taunt_armswing", "cfalcon_taunt_salute", "falcon_hoyah", "falcon_uspec1", "falcon_uspec2", "falcon_hyesz", "falcon_utiltCrash", "falcon_dspec", "falcon_starKO", "falcon_victory", "falcon_victory_v2", "falcon_charge"]
            });
        }

        public function getCaptainFalcon():Object
        {
            var _local_1:Object = new Object();
            _local_1 = {
                "classAPI":CaptainExt,
                "statsName":"captainfalcon",
                "displayName":"Captain Falcon",
                "linkage_id":"falcon",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"captainfalcon_head",
                "seriesIcon":"fzero",
                "width":22,
                "height":58,
                "tiltTossMultiplier":1,
                "smashTossMultiplier":1.2,
                "shield_scale":1.1,
                "jumpSpeed":20,
                "jumpSpeedMidair":20,
                "jumpStartup":2,
                "shortHopSpeed":12,
                "max_jumpSpeed":8,
                "groundToAirMultiplier":0.929,
                "dodgeSpeed":16,
                "dodgeDecel":-1.35,
                "gravity":1.65,
                "weight1":104,
                "power":"captainfalcon",
                "norm_xSpeed":5.6,
                "max_xSpeed":14,
                "max_ySpeed":15,
                "fastFallSpeed":18,
                "accel_start":0.355,
                "accel_start_dash":1.1,
                "accel_rate":0.9,
                "accel_rate_air":0.85,
                "decel_rate":-1.35,
                "decel_rate_air":-0.2,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":10,
                "tetherGrab":false,
                "roll_speed":32,
                "roll_decay":0.7,
                "getup_roll_delay":2,
                "tech_roll_delay":5,
                "climb_roll_delay":8,
                "itemScaleRatio":0.869565217,
                "special_type":6,
                "finalSmashCutin":"cf_fs_cutin",
                "normalStats_id":"captainfalcon",
                "specialStats_id":null,
                "sounds":{
                    "jump":"falcon_jump",
                    "jump_midair":null,
                    "hurt":"falcon_hurt",
                    "hurt2":"falcon_hurt2",
                    "hurtBad":"falcon_hurtBad",
                    "hurtBad2":"falcon_hurtBad2",
                    "dead":"falcon_death",
                    "dead2":"falcon_death2",
                    "pummel":"brawl_kick_s",
                    "screenko":"falcon_hurtBad2",
                    "starko":"falcon_starKO",
                    "ledge_grab":null,
                    "winTheme":"falcon_victory_v2"
                },
                "hurtFrames":5,
                "grabDamage":1,
                "fs_time_limit":210
            };
            var _local_2:Object = new Object();
            _local_2 = {
                "a":{
                    "canFallOff":false,
                    "cpuAttackQueue":"crouch_attack",
                    "reenableTimer":15,
                    "attackVoice1_id":"cfalcon_grunt1",
                    "attackVoice2_id":"cfalcon_grunt2",
                    "attackVoice3_id":"cfalcon_grunt3",
                    "attackVoice4_id":"cfalcon_grunt4",
                    "attackSound1_id":"cfalcon_swing_s",
                    "attackSound2_id":"cfalcon_swing_m",
                    "attackSound3_id":"cfalcon_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":2,
                            "priority":1,
                            "hitStun":2,
                            "selfHitStun":1,
                            "hitLag":-1.1,
                            "effect_id":"effect_hit2",
                            "direction":60,
                            "power":20,
                            "kbConstant":40,
                            "effectSound":"brawl_punch_m"
                        },
                        "attackBox2":{
                            "damage":2,
                            "priority":1,
                            "hitStun":2,
                            "selfHitStun":1,
                            "hitLag":-1.1,
                            "effect_id":"effect_hit2",
                            "direction":60,
                            "power":20,
                            "kbConstant":40,
                            "effectSound":"brawl_punch_m"
                        }
                    }
                },
                "a_up":{
                    "cancelWhenAirborne":false,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"falcon_hoyah",
                    "attackSound1_id":"cfalcon_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":14,
                            "priority":4,
                            "camShake":4,
                            "effect_id":"effect_heavyHit",
                            "direction":90,
                            "power":0,
                            "weightKB":20,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":8,
                            "priority":4,
                            "camShake":4,
                            "effect_id":"effect_heavyHit",
                            "direction":90,
                            "power":0,
                            "weightKB":80,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox3":{
                            "damage":8,
                            "priority":4,
                            "camShake":4,
                            "effect_id":"effect_heavyHit",
                            "direction":125,
                            "power":0,
                            "weightKB":80,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_up_tilt":{
                    "xSpeedDecay":-2.8,
                    "canFallOff":false,
                    "attackVoice1_id":"cfalcon_grunt1",
                    "attackVoice2_id":"cfalcon_grunt4",
                    "attackVoice3_id":"cfalcon_grunt2",
                    "attackVoice4_id":"cfalcon_grunt3",
                    "attackSound1_id":"cfalcon_swing_l",
                    "attackSound2_id":"cfalcon_swing_s",
                    "attackSound3_id":"falcon_utiltCrash",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":13,
                            "priority":3,
                            "effect_id":"effect_hit2",
                            "direction":50,
                            "power":50,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":13,
                            "priority":3,
                            "effect_id":"effect_hit2",
                            "direction":50,
                            "power":50,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox3":{
                            "damage":10,
                            "priority":4,
                            "camShake":4,
                            "effect_id":"effect_heavyHit",
                            "direction":270,
                            "power":30,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_forward":{
                    "xSpeedDecay":-1.3,
                    "canFallOff":false,
                    "attackVoice1_id":"cfalcon_grunt1",
                    "attackVoice2_id":"cfalcon_grunt2",
                    "attackVoice3_id":"cfalcon_grunt3",
                    "attackVoice4_id":"cfalcon_grunt4",
                    "attackSound1_id":"cfalcon_swing_ll",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":3,
                            "hitLag":-1,
                            "effect_id":"effect_hit1",
                            "direction":60,
                            "power":62,
                            "kbConstant":70,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_forward_tilt":{
                    "xSpeedDecay":-1,
                    "canFallOff":false,
                    "attackVoice1_id":"cfalcon_grunt1",
                    "attackVoice2_id":"cfalcon_grunt4",
                    "attackVoice3_id":"cfalcon_grunt2",
                    "attackVoice4_id":"cfalcon_grunt3",
                    "attackSound1_id":"cfalcon_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":3,
                            "hitLag":-1,
                            "effect_id":"effect_hit1",
                            "direction":45,
                            "power":10,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"falcon_peturar",
                    "attackSound1_id":"cfalcon_swing_ll",
                    "attackBoxes":{"attackBox":{
                            "damage":19,
                            "priority":5,
                            "camShake":6,
                            "effect_id":"effect_firehit_heavy",
                            "direction":43,
                            "power":25,
                            "kbConstant":95,
                            "burn":true,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_down":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"falcon_toorar",
                    "attackSound1_id":"cfalcon_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":18,
                            "priority":6,
                            "effect_id":"effect_heavyHit",
                            "direction":38,
                            "power":40,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_air":{
                    "hit_ease":3.85,
                    "allowControl":true,
                    "cancelWhenAirborne":true,
                    "canFallOff":true,
                    "maintainSpeed":true,
                    "attackVoice1_id":"cfalcon_grunt1",
                    "attackVoice2_id":"cfalcon_grunt2",
                    "attackVoice3_id":"cfalcon_grunt3",
                    "attackVoice4_id":"cfalcon_grunt4",
                    "attackSound1_id":"cfalcon_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":5,
                            "priority":2,
                            "hitStun":2,
                            "selfHitStun":1,
                            "hitLag":-1.3,
                            "effect_id":"effect_hit2",
                            "direction":50,
                            "reversableAngle":false,
                            "power":0,
                            "kbConstant":80,
                            "weightKB":50,
                            "effectSound":"brawl_punch_m"
                        },
                        "attackBox2":{
                            "damage":4,
                            "priority":2,
                            "hitStun":2,
                            "selfHitStun":1,
                            "hitLag":-1.3,
                            "effect_id":"effect_hit2",
                            "direction":50,
                            "power":0,
                            "kbConstant":80,
                            "weightKB":50,
                            "effectSound":"brawl_punch_m"
                        }
                    }
                },
                "a_air_up":{
                    "allowControl":true,
                    "cancelWhenAirborne":true,
                    "canFallOff":true,
                    "attackVoice1_id":"cfalcon_grunt1",
                    "attackVoice2_id":"cfalcon_grunt2",
                    "attackVoice3_id":"cfalcon_grunt3",
                    "attackVoice4_id":"cfalcon_grunt4",
                    "attackSound1_id":"cfalcon_swing_ll",
                    "cpuAttackQueue":"a_air;a_air_forward;a_air_down",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":11,
                            "priority":3,
                            "hitLag":-1.1,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":45,
                            "power":25,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":10,
                            "priority":3,
                            "hitLag":-1.1,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":45,
                            "power":25,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_air_forward":{
                    "allowControl":true,
                    "cancelWhenAirborne":true,
                    "canFallOff":true,
                    "allowControlGround":false,
                    "cpuAttackQueue":"a",
                    "canUseInAir":true,
                    "attackVoice1_id":"cfalcon_grunt1",
                    "attackVoice2_id":"cfalcon_grunt2",
                    "attackVoice3_id":"cfalcon_grunt3",
                    "attackVoice4_id":"cfalcon_grunt4",
                    "attackSound1_id":"cfalcon_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":18,
                            "priority":5,
                            "camShake":4,
                            "hitStun":7,
                            "selfHitStun":4,
                            "effect_id":"effect_elechit_heavy",
                            "direction":40,
                            "power":35,
                            "kbConstant":93,
                            "shock":true,
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox2":{
                            "damage":18,
                            "priority":5,
                            "camShake":4,
                            "hitStun":7,
                            "selfHitStun":4,
                            "effect_id":"effect_elechit_heavy",
                            "direction":40,
                            "power":35,
                            "kbConstant":93,
                            "shock":true,
                            "effectSound":"brawl_kick_l"
                        }
                    }
                },
                "a_air_backward":{
                    "allowControl":true,
                    "cancelWhenAirborne":true,
                    "canFallOff":true,
                    "allowControlGround":false,
                    "attackVoice1_id":"cfalcon_grunt1",
                    "attackVoice2_id":"cfalcon_grunt4",
                    "attackVoice3_id":"cfalcon_grunt2",
                    "attackVoice4_id":"cfalcon_grunt3",
                    "attackSound1_id":"cfalcon_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":14,
                            "priority":4,
                            "hitStun":5,
                            "selfHitStun":2,
                            "hitLag":-1.1,
                            "effect_id":"effect_heavyHit",
                            "direction":47,
                            "power":20,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_m"
                        },
                        "attackBox2":{
                            "damage":12,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":1,
                            "hitLag":-1.1,
                            "effect_id":"effect_heavyHit",
                            "direction":47,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_m"
                        }
                    }
                },
                "a_air_down":{
                    "allowControl":true,
                    "allowControlGround":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":true,
                    "cpuAttackQueue":"a_air_up;a_air_forward;a_air",
                    "attackVoice1_id":"cfalcon_grunt1",
                    "attackVoice2_id":"cfalcon_grunt4",
                    "attackVoice3_id":"cfalcon_grunt2",
                    "attackVoice4_id":"cfalcon_grunt3",
                    "attackSound1_id":"cfalcon_swing_ll",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":12,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":270,
                            "power":40,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":16,
                            "priority":4,
                            "effect_id":"effect_heavyHit",
                            "direction":291,
                            "power":40,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_l"
                        }
                    }
                },
                "b":{
                    "canFallOff":false,
                    "chargeInAir":false,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "attackVoice1_id":"falcon_",
                    "attackVoice2_id":"pawnch",
                    "attackSound1_id":"fPunchCharge",
                    "attackSound2_id":"fPunchSwing",
                    "attackSound3_id":"fPunchImpact",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":25,
                            "priority":7,
                            "camShake":15,
                            "effect_id":"effect_firehit_heavy",
                            "direction":40,
                            "power":45,
                            "kbConstant":100,
                            "hitStun":10,
                            "selfHitStun":8,
                            "burn":true,
                            "effectSound":"cfalcon_nspecial_hit"
                        },
                        "attackBox2":{
                            "damage":25,
                            "priority":7,
                            "camShake":15,
                            "effect_id":"effect_firehit_heavy",
                            "direction":40,
                            "power":45,
                            "kbConstant":100,
                            "hitStun":10,
                            "selfHitStun":8,
                            "burn":true,
                            "effectSound":"cfalcon_nspecial_hit"
                        }
                    }
                },
                "b_air":{
                    "allowControl":true,
                    "allowControlGround":false,
                    "canFallOff":false,
                    "chargeInAir":false,
                    "canUseInAir":true,
                    "attackVoice1_id":"falcon_",
                    "attackVoice2_id":"pawnch",
                    "attackSound1_id":"fPunchCharge",
                    "attackSound2_id":"fPunchSwing",
                    "attackSound3_id":"fPunchImpact",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":23,
                            "priority":7,
                            "camShake":15,
                            "effect_id":"effect_firehit_heavy",
                            "direction":40,
                            "power":35,
                            "kbConstant":100,
                            "hitStun":9,
                            "selfHitStun":7,
                            "burn":true,
                            "effectSound":"cfalcon_nspecial_hit"
                        },
                        "attackBox2":{
                            "damage":23,
                            "priority":7,
                            "camShake":15,
                            "effect_id":"effect_firehit_heavy",
                            "direction":40,
                            "power":35,
                            "kbConstant":100,
                            "hitStun":9,
                            "selfHitStun":7,
                            "burn":true,
                            "effectSound":"cfalcon_nspecial_hit"
                        }
                    }
                },
                "b_up":{
                    "cancelWhenAirborne":false,
                    "xSpeedAccelAir":0.85,
                    "air_ease":2,
                    "stale":false,
                    "isRecoveryMove":true,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "attackVoice1_id":"falcon_hyesz",
                    "attackSound1_id":"falcon_uspec1",
                    "attackSound2_id":"bombexplode",
                    "attackSound3_id":"falcon_uspec2",
                    "attackBoxes":{"attackBox":{
                            "damage":14,
                            "priority":4,
                            "camShake":4,
                            "direction":45,
                            "power":78,
                            "kbConstant":55,
                            "burn":true,
                            "bypassGrabbed":true,
                            "bypassShield":true,
                            "effect_id":"effect_firehit_heavy",
                            "effectSound":null
                        }}
                },
                "b_up_air":{
                    "xSpeedAccelAir":0.85,
                    "air_ease":1.8,
                    "cancelWhenAirborne":false,
                    "isRecoveryMove":true,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "attackVoice1_id":"falcon_hyesz",
                    "attackSound1_id":"falcon_uspec1",
                    "attackSound2_id":"bombexplode",
                    "attackSound3_id":"falcon_uspec2",
                    "attackBoxes":{"attackBox":{
                            "damage":14,
                            "priority":0,
                            "direction":45,
                            "power":78,
                            "kbConstant":55,
                            "burn":true,
                            "bypassGrabbed":true,
                            "bypassShield":true,
                            "effect_id":"effect_firehit_heavy",
                            "effectSound":null
                        }}
                },
                "b_forward":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":-0.7777777,
                    "isLongRangeMove":true,
                    "cpuAttackQueue":"a_air_down;a_air;a_up;a_air_forward",
                    "attackSound1_id":"raptorBoost1",
                    "attackSound2_id":"raptorBoost2",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "hitLag":-1.1,
                            "direction":90,
                            "reversableAngle":false,
                            "power":70,
                            "kbConstant":65,
                            "burn":true,
                            "effect_id":"effect_firehit_light",
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "b_forward_air":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":-0.7777777,
                    "xSpeedDecayAir":-0.7777777,
                    "air_ease":0,
                    "disableForCPU":true,
                    "attackSound1_id":"raptorBoost1",
                    "attackSound2_id":"raptorBoost2",
                    "attackBoxes":{"attackBox":{
                            "forceTumbleFall":true,
                            "damage":9,
                            "hitLag":-1.1,
                            "direction":270,
                            "reversableAngle":false,
                            "power":40,
                            "kbConstant":50,
                            "burn":true,
                            "effect_id":"effect_firehit_light",
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "b_down":{
                    "air_ease":0.5,
                    "cancelWhenAirborne":false,
                    "disableForCPU":true,
                    "attackVoice1_id":"falcon_kick",
                    "attackSound1_id":"falcon_dspec",
                    "attackSound2_id":"falcon_dspecLand",
                    "attackBoxes":{"attackBox":{
                            "damage":15,
                            "priority":4,
                            "effect_id":"effect_firehit_heavy",
                            "direction":60,
                            "power":40,
                            "kbConstant":55,
                            "burn":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "b_down_air":{
                    "resetMovement":true,
                    "air_ease":1,
                    "isHorizontalRecoveryMove":true,
                    "disableForCPU":true,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "attackVoice1_id":"falcon_kick",
                    "attackSound1_id":"falcon_dspec",
                    "attackSound2_id":"falcon_dspecLand",
                    "attackBoxes":{"attackBox":{
                            "damage":15,
                            "priority":4,
                            "effect_id":"effect_firehit_heavy",
                            "direction":60,
                            "power":40,
                            "kbConstant":55,
                            "burn":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "throw_up":{
                    "resetMovement":true,
                    "xSpeedDecay":-0.1,
                    "canFallOff":false,
                    "cpuAttackQueue":"a_air;a_air_forward;a_air_down;a_air_up",
                    "attackVoice1_id":"cfalcon_grunt1",
                    "attackVoice2_id":"cfalcon_grunt4",
                    "attackVoice3_id":"cfalcon_grunt2",
                    "attackVoice4_id":"cfalcon_grunt3",
                    "attackSound1_id":"cfalcon_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "bypassGrabbed":true,
                            "direction":45,
                            "power":60,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_l",
                            "effect_id":"effect_heavyHit"
                        },
                        "attackBox2":{
                            "damage":7,
                            "bypassNonGrabbed":true,
                            "forceTumbleFall":true,
                            "priority":2,
                            "effect_id":"effect_hit2",
                            "hitStun":0,
                            "selfHitStun":0,
                            "direction":80,
                            "reversableAngle":false,
                            "power":75,
                            "kbConstant":60,
                            "hitLag":-1.2,
                            "effectSound":"brawl_punch_l"
                        }
                    }
                },
                "throw_forward":{
                    "resetMovement":true,
                    "xSpeedDecay":-0.1,
                    "canFallOff":false,
                    "attackVoice1_id":"cfalcon_grunt1",
                    "attackVoice2_id":"cfalcon_grunt4",
                    "attackVoice3_id":"cfalcon_grunt2",
                    "attackVoice4_id":"cfalcon_grunt3",
                    "attackSound1_id":"cfalcon_swing_s",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "bypassGrabbed":true,
                            "direction":45,
                            "power":60,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_l",
                            "effect_id":"effect_heavyHit"
                        },
                        "attackBox2":{
                            "damage":4,
                            "bypassNonGrabbed":true,
                            "priority":3,
                            "effect_id":"effect_hit2",
                            "direction":30,
                            "reversableAngle":false,
                            "power":40,
                            "kbConstant":105,
                            "effectSound":"brawl_punch_l"
                        }
                    }
                },
                "throw_back":{
                    "resetMovement":true,
                    "xSpeedDecay":-0.1,
                    "canFallOff":false,
                    "attackVoice1_id":"cfalcon_grunt1",
                    "attackVoice2_id":"cfalcon_grunt4",
                    "attackVoice3_id":"cfalcon_grunt2",
                    "attackVoice4_id":"cfalcon_grunt3",
                    "attackSound1_id":"cfalcon_swing_s",
                    "attackSound2_id":"cfalcon_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "bypassGrabbed":true,
                            "direction":45,
                            "power":60,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_l",
                            "effect_id":"effect_heavyHit"
                        },
                        "attackBox2":{
                            "damage":5,
                            "bypassNonGrabbed":true,
                            "direction":160,
                            "power":35,
                            "kbConstant":110,
                            "effect_id":"effect_hit2",
                            "effectSound":"brawl_kick_l",
                            "reversableAngle":false
                        }
                    }
                },
                "throw_down":{
                    "resetMovement":true,
                    "xSpeedDecay":-0.1,
                    "canFallOff":false,
                    "cpuAttackQueue":"a_air;a_air_forward;a_air_up",
                    "attackVoice1_id":"cfalcon_grunt1",
                    "attackVoice2_id":"cfalcon_grunt4",
                    "attackVoice3_id":"cfalcon_grunt2",
                    "attackVoice4_id":"cfalcon_grunt3",
                    "attackSound1_id":"cfalcon_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "bypassNonGrabbed":true,
                            "hitLag":-1.2,
                            "priority":3,
                            "forceTumbleFall":true,
                            "effect_id":"effect_hit2",
                            "direction":65,
                            "reversableAngle":false,
                            "power":75,
                            "kbConstant":35,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "crouch_attack":{
                    "xSpeedDecay":-1.9,
                    "canFallOff":false,
                    "attackVoice1_id":"cfalcon_grunt1",
                    "attackVoice2_id":"cfalcon_grunt4",
                    "attackVoice3_id":"cfalcon_grunt2",
                    "attackVoice4_id":"cfalcon_grunt3",
                    "attackSound1_id":"cfalcon_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":12,
                            "priority":2,
                            "hitLag":-1.1,
                            "effect_id":"effect_hit1",
                            "direction":80,
                            "power":25,
                            "kbConstant":75,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":12,
                            "priority":2,
                            "hitLag":-1.1,
                            "effect_id":"effect_hit1",
                            "direction":70,
                            "power":25,
                            "kbConstant":75,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox3":{
                            "damage":12,
                            "priority":2,
                            "hitLag":-1.1,
                            "effect_id":"effect_hit1",
                            "direction":60,
                            "power":25,
                            "kbConstant":75,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "ledge_attack":{
                    "xSpeedDecay":-1,
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackVoice1_id":"cfalcon_grunt1",
                    "attackVoice2_id":"cfalcon_grunt4",
                    "attackVoice3_id":"cfalcon_grunt2",
                    "attackVoice4_id":"cfalcon_grunt3",
                    "attackSound1_id":"cfalcon_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "direction":45,
                            "power":75,
                            "kbConstant":25,
                            "effect_id":"effect_hit2",
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "getup_attack":{
                    "xSpeedDecay":-1,
                    "attackVoice1_id":"cfalcon_grunt1",
                    "attackVoice2_id":"cfalcon_grunt4",
                    "attackVoice3_id":"cfalcon_grunt2",
                    "attackVoice4_id":"cfalcon_grunt3",
                    "attackSound1_id":"cfalcon_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":4,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":80,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "kirby":{
                    "attackDelay":4,
                    "xSpeedDecay":-0.5,
                    "canFallOff":false,
                    "chargeInAir":false,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "attackSound1_id":"fPunchCharge",
                    "attackSound2_id":"fPunchSwing",
                    "attackSound3_id":"fPunchImpact",
                    "attackBoxes":{"attackBox":{
                            "damage":27,
                            "priority":7,
                            "camShake":3,
                            "effect_id":"effect_firehit_heavy",
                            "direction":45,
                            "power":30,
                            "kbConstant":102,
                            "burn":true,
                            "bypassGrabbed":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "kirby_air":{
                    "attackDelay":4,
                    "xSpeedDecay":-0.5,
                    "canFallOff":false,
                    "chargeInAir":false,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "attackSound1_id":"fPunchCharge",
                    "attackSound2_id":"fPunchSwing",
                    "attackSound3_id":"fPunchImpact",
                    "attackBoxes":{"attackBox":{
                            "damage":27,
                            "priority":7,
                            "camShake":3,
                            "effect_id":"effect_firehit_heavy",
                            "direction":45,
                            "power":30,
                            "kbConstant":102,
                            "burn":true,
                            "bypassGrabbed":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "air_ease":0,
                    "canUseInAir":true,
                    "attackVoice1_id":"falcon_finalSmash",
                    "attackVoice2_id":"blueFalcon",
                    "attackBoxes":{"attackBox":{
                            "damage":30,
                            "priority":7,
                            "selfHitStun":0,
                            "camShake":14,
                            "direction":45,
                            "power":55,
                            "kbConstant":110,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "item_jab":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_tilt":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_dash":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_smash":{
                    "chargetime_max":40,
                    "chargeClick":true,
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false,
                    "attackVoice1_id":"cfalcon_grunt3"
                },
                "item_homerun":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false,
                    "attackVoice1_id":"cfalcon_grunt4"
                },
                "item_fan":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_shoot":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "canFallOff":false
                },
                "item_heavyshoot":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "canFallOff":false
                },
                "item_raise":{
                    "maintainSpeed":false,
                    "canFallOff":false
                },
                "item_float":{
                    "maintainSpeed":true,
                    "canFallOff":true
                },
                "item_screw":{
                    "refreshRate":1,
                    "allowControl":true,
                    "air_ease":0,
                    "maintainSpeed":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "attackBoxes":{
                        "attackBox":{
                            "damage":1,
                            "priority":5,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":95,
                            "power":125,
                            "kbConstant":10,
                            "stackKnockback":false,
                            "shock":true,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox2":{
                            "damage":1,
                            "priority":5,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":95,
                            "power":125,
                            "kbConstant":10,
                            "stackKnockback":false,
                            "shock":true,
                            "effectSound":"brawl_kick_s"
                        }
                    }
                },
                "item_firedash":{
                    "allowControl":false,
                    "air_ease":0,
                    "maintainSpeed":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "effect_id":"effect_firehit_heavy",
                            "direction":45,
                            "power":25,
                            "kbConstant":110,
                            "burn":true,
                            "effectSound":"brawl_fire_l"
                        }}
                },
                "item_bubblebounce":{
                    "allowControl":true,
                    "air_ease":-1,
                    "maintainSpeed":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "xSpeedCap":6,
                    "xSpeedAccel":0.75,
                    "xSpeedAccelAir":0.75,
                    "xSpeedDecay":0.99,
                    "xSpeedDecayAir":0.99,
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "effect_id":"effect_waterhit_heavy",
                            "direction":270,
                            "power":20,
                            "kbConstant":80,
                            "effectSound":"sfx_waterhit_m"
                        }}
                }
            };
            var _local_3:Object = {
                "captainfalcon_nspecProj":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"captainfalcon_nspec_proj",
                    "width":30,
                    "height":36,
                    "limitOverwrite":true,
                    "time_max":600,
                    "gravity":0,
                    "maxgravity":0,
                    "canBeReversed":false
                },
                "captainfalcon_dspecairProj":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"captainfalcon_dspecair_proj",
                    "width":30,
                    "height":36,
                    "limitOverwrite":true,
                    "time_max":600,
                    "gravity":0,
                    "maxgravity":0,
                    "canBeReversed":false
                },
                "captainfalcon_dspecProj":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"captainfalcon_dspec_proj",
                    "width":30,
                    "height":36,
                    "limitOverwrite":true,
                    "time_max":600,
                    "gravity":0,
                    "maxgravity":0,
                    "canBeReversed":false
                }
            };
            var _local_4:Object;
            return {
                "cData":_local_1,
                "aData":_local_2,
                "pData":_local_3,
                "iData":_local_4
            };
        }


    }
}

