package
{
    import flash.display.MovieClip;

    public dynamic class Main extends SSF2Asset
    {

        public var stance:MovieClip;

        public function Main()
        {
            super();
            register("id", "bandanadee");
            register("guid", "d445439f-d1bc-4b9e-be8b-cb156f498f38");
            register("characters", [this.getBandanaDee()]);
            register("resources", {
                "movieclips":["dairSparkle", "b", "deeFinalSmashProjectile", "a", "ness_fairSpark", "dee_nspec", "dee_finalsmash", "dee_spear", "bandanadee", "kirby_powerstar", "dream_land", "hat_chibirobo", "kirby_hat_test", "Kirby_Symbol", "dee_head", "dee_fsmash_water"],
                "sounds":["bandanadee_airspin", "bandanadee_attackstar", "bandanadee_crouch1", "bandanadee_crouch2", "bandanadee_dashstart", "bandanadee_dashstop", "bandanadee_dspecSpin", "bandanadee_entrance", "bandanadee_fspecEnd", "bandanadee_jump1", "bandanadee_jump2", "bandanadee_magic_l", "bandanadee_magic_m", "bandanadee_magic_s", "bandanadee_magic_spin", "bandanadee_powersteal", "bandanadee_spit", "bandanadee_star", "bandanadee_starKO", "bandanadee_step01", "bandanadee_step02", "bandanadee_swing_l", "bandanadee_swing_ll", "bandanadee_swing_m", "bandanadee_swing_s", "bandanadee_taunt", "bandanadee_uspecJump", "bandanadee_uspecSpin", "KirbyVictory", "kirbywin", "bandanadee_land1"]
            });
        }

        public function getBandanaDee():Object
        {
            var _local_1:Object = new Object();
            _local_1 = {
                "classAPI":BandanaDeeExt,
                "statsName":"bandanadee",
                "displayName":"Bandana Dee",
                "linkage_id":"bandanadee",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"dee_head",
                "seriesIcon":"Kirby_Symbol",
                "width":30,
                "height":41,
                "jumpSpeed":14.3,
                "jumpSpeedMidair":13.3,
                "jumpStartup":2,
                "shortHopSpeed":10,
                "max_jumpSpeed":6.8,
                "groundToAirMultiplier":0.87,
                "maxShieldSize":1.15,
                "minShieldSize":0.2,
                "midAirTurn":true,
                "dodgeSpeed":15,
                "dodgeDecel":-0.95,
                "gravity":1.2,
                "weight1":76,
                "power":"bandanadee",
                "norm_xSpeed":4,
                "max_xSpeed":10.5,
                "max_ySpeed":10,
                "fastFallSpeed":15,
                "accel_start":0.5,
                "accel_start_dash":1.145,
                "accel_rate":0.9,
                "accel_rate_air":1.5,
                "decel_rate":-1.07,
                "decel_rate_air":-0.075,
                "holdJump":false,
                "max_jump":3,
                "max_projectile":10,
                "tetherGrab":false,
                "roll_speed":30,
                "roll_decay":0.7,
                "getup_roll_delay":3,
                "tech_roll_delay":4,
                "climb_roll_delay":9,
                "itemScaleRatio":0.869565217391304,
                "special_type":1,
                "finalSmashCutin":"bdee_fs_cutin",
                "normalStats_id":"bandanadee",
                "specialStats_id":null,
                "sounds":{
                    "jump":null,
                    "jump_midair":null,
                    "hurt":"ssf2_snd_vfx_bdee_hurt01",
                    "hurt2":"ssf2_snd_vfx_bdee_hurt02",
                    "hurtBad":"ssf2_snd_vfx_bdee_hurtbad01",
                    "hurtBad2":"ssf2_snd_vfx_bdee_hurtbad02",
                    "dead":"ssf2_snd_vfx_bdee_dead01",
                    "dead2":"ssf2_snd_vfx_bdee_dead02",
                    "pummel":"brawl_punch_s",
                    "screenko":null,
                    "starko":"bandanadee_starKO",
                    "ledge_grab":null,
                    "winTheme":"KirbyVictory"
                },
                "hurtFrames":5,
                "grabDamage":1
            };
            var _local_2:Object = new Object();
            _local_2 = {
                "a":{
                    "combo_max":999,
                    "holdRepeat":true,
                    "canFallOff":false,
                    "reenableTimer":6,
                    "attackVoice1_id":"ssf2_snd_vfx_bdee_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_bdee_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_bdee_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_bdee_attack04",
                    "attackSound1_id":"bandanadee_swing_s",
                    "attackSound2_id":"bandanadee_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":2,
                            "priority":1,
                            "hitLag":-1.1,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":50,
                            "power":15,
                            "kbConstant":30,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":2,
                            "priority":1,
                            "hitLag":-1.1,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":50,
                            "power":15,
                            "kbConstant":30,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox3":{
                            "damage":2,
                            "priority":1,
                            "hitLag":-1.1,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":50,
                            "power":15,
                            "kbConstant":30,
                            "effectSound":"sw_brawl_hit_S"
                        }
                    }
                },
                "a_up":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"ssf2_snd_vfx_bdee_usmash",
                    "attackSound1_id":"bandanadee_swing_l",
                    "attackSound2_id":"bandanadee_magic_spin",
                    "attackSound3_id":"bandanadee_magic_l",
                    "attackBoxes":{"attackBox":{
                            "sdiDistance":1,
                            "damage":0.5,
                            "priority":4,
                            "hitLag":-1.3,
                            "effect_id":"effect_swordSlash",
                            "direction":190,
                            "power":25,
                            "kbConstant":10,
                            "effectSound":"brawl_zap_s"
                        }}
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "cpuAttackQueue":"a_air_up;a_air_backward",
                    "attackVoice1_id":"ssf2_snd_vfx_bdee_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_bdee_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_bdee_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_bdee_attack04",
                    "attackSound1_id":"bandanadee_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":7,
                            "priority":3,
                            "hitLag":-1,
                            "effect_id":"effect_lightHit",
                            "direction":85,
                            "power":50,
                            "kbConstant":100,
                            "effectSound":"sw_brawl_hit_M"
                        },
                        "attackBox2":{
                            "damage":7,
                            "priority":3,
                            "hitLag":-1,
                            "effect_id":"effect_lightHit",
                            "direction":85,
                            "power":50,
                            "kbConstant":100,
                            "effectSound":"sw_brawl_hit_M"
                        }
                    }
                },
                "a_forward":{
                    "refreshRate":999,
                    "allowControl":false,
                    "canFallOff":false,
                    "cancelWhenAirborne":false,
                    "attackVoice1_id":"ssf2_snd_vfx_bdee_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_bdee_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_bdee_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_bdee_attack04",
                    "attackSound1_id":"bandanadee_jump1",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitLag":-1.2,
                            "effect_id":"effect_swordSlash",
                            "direction":40,
                            "reversableAngle":false,
                            "power":80,
                            "kbConstant":0,
                            "effectSound":"sw_brawl_hit_M"
                        },
                        "attackBox2":{
                            "damage":4,
                            "priority":2,
                            "hitLag":-1.2,
                            "effect_id":"effect_swordSlash",
                            "direction":40,
                            "reversableAngle":false,
                            "power":80,
                            "kbConstant":0,
                            "effectSound":"sw_brawl_hit_M"
                        }
                    }
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"ssf2_snd_vfx_bdee_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_bdee_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_bdee_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_bdee_attack04",
                    "attackSound1_id":"bandanadee_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":2,
                            "hitLag":-1.1,
                            "effect_id":"effect_lightHit",
                            "direction":40,
                            "power":20,
                            "kbConstant":100,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "a_forwardsmash":{
                    "xSpeedDecay":-1,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"ssf2_snd_vfx_bdee_fsmash",
                    "attackSound1_id":"bandanadee_swing_l",
                    "attackSound2_id":"bandanadee_magic_m",
                    "attackBoxes":{"attackBox":{
                            "damage":13.5,
                            "priority":6,
                            "effect_id":"effect_waterhit_heavy",
                            "direction":45,
                            "power":42,
                            "kbConstant":90,
                            "effectSound":"sfx_waterhit_l"
                        }}
                },
                "a_down":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"ssf2_snd_vfx_bdee_dsmash",
                    "attackSound1_id":"bandanadee_swing_ll",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":13,
                            "priority":5,
                            "hitLag":-1.1,
                            "effect_id":"effect_heavyHit",
                            "direction":75,
                            "power":30,
                            "kbConstant":100,
                            "effectSound":"sw_brawl_hit_H"
                        },
                        "attackBox2":{
                            "damage":12,
                            "priority":5,
                            "hitLag":-1.1,
                            "effect_id":"effect_heavyHit",
                            "direction":75,
                            "power":30,
                            "kbConstant":100,
                            "effectSound":"sw_brawl_hit_H"
                        },
                        "attackBox3":{
                            "damage":12,
                            "priority":5,
                            "hitLag":-1.1,
                            "effect_id":"effect_heavyHit",
                            "direction":75,
                            "power":30,
                            "kbConstant":100,
                            "effectSound":"sw_brawl_hit_H"
                        }
                    }
                },
                "a_air":{
                    "cancelSoundOnEnd":true,
                    "refreshRate":999,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"ssf2_snd_vfx_bdee_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_bdee_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_bdee_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_bdee_attack04",
                    "attackSound1_id":"bandanadee_airspin",
                    "attackBoxes":{"attackBox":{
                            "damage":1.5,
                            "priority":3,
                            "hitLag":5,
                            "effect_id":"effect_lightHit",
                            "direction":60,
                            "reversableAngle":false,
                            "power":50,
                            "kbConstant":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "a_air_up":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "maintainSpeed":true,
                    "cpuAttackQueue":"a_air_up;a_air_backward",
                    "attackVoice1_id":"ssf2_snd_vfx_bdee_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_bdee_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_bdee_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_bdee_attack04",
                    "attackSound1_id":"bandanadee_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":13,
                            "priority":2,
                            "effect_id":"effect_heavyHit",
                            "direction":88,
                            "power":45,
                            "kbConstant":95,
                            "effectSound":"sw_brawl_hit_H"
                        },
                        "attackBox2":{
                            "damage":12,
                            "priority":2,
                            "effect_id":"effect_heavyHit",
                            "direction":85,
                            "power":40,
                            "kbConstant":90,
                            "effectSound":"sw_brawl_hit_M"
                        }
                    }
                },
                "a_air_forward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"ssf2_snd_vfx_bdee_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_bdee_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_bdee_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_bdee_attack04",
                    "attackSound1_id":"bandanadee_swing_m",
                    "attackSound2_id":"bandanadee_magic_s",
                    "attackSound3_id":"bandanadee_magic_spin",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":2,
                            "priority":2,
                            "hitLag":5,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":45,
                            "reversableAngle":false,
                            "power":30,
                            "kbConstant":0,
                            "effectSound":"brawl_zap_s"
                        },
                        "attackBox2":{
                            "damage":2,
                            "priority":2,
                            "hitLag":5,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":45,
                            "reversableAngle":false,
                            "power":30,
                            "kbConstant":0,
                            "effectSound":"brawl_zap_s"
                        }
                    }
                },
                "a_air_backward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"ssf2_snd_vfx_bdee_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_bdee_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_bdee_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_bdee_attack04",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":3,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":140,
                            "reversableAngle":false,
                            "power":35,
                            "kbConstant":105,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_air_down":{
                    "refreshRate":4,
                    "allowControl":false,
                    "cancelSoundOnEnd":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "cpuAttackQueue":"throw_down",
                    "reenableTimer":20,
                    "attackVoice1_id":"ssf2_snd_vfx_bdee_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_bdee_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_bdee_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_bdee_attack04",
                    "attackSound1_id":"bandanadee_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":2,
                            "priority":2,
                            "effect_id":"effect_heavyHit",
                            "direction":250,
                            "power":32,
                            "kbConstant":32,
                            "effectSound":"sw_brawl_hit_H"
                        },
                        "attackBox2":{
                            "damage":2,
                            "priority":2,
                            "effect_id":"effect_heavyHit",
                            "direction":250,
                            "power":32,
                            "kbConstant":32,
                            "effectSound":"sw_brawl_hit_M"
                        }
                    }
                },
                "b":{
                    "allowControlGround":false,
                    "refreshRate":4,
                    "attackVoice1_id":"ssf2_snd_vfx_bdee_usmash",
                    "attackSound1_id":"bandanadee_magic_m",
                    "attackSound2_id":"bandanadee_magic_l",
                    "canFallOff":false,
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":-1,
                            "direction":60,
                            "reversableAngle":false,
                            "hitStun":1,
                            "selfHitStun":1,
                            "power":30,
                            "kbConstant":50,
                            "effectSound":"brawl_zap_s",
                            "shock":true
                        }}
                },
                "b_air":{
                    "allowControlGround":false,
                    "refreshRate":4,
                    "attackVoice1_id":"ssf2_snd_vfx_bdee_usmash",
                    "attackSound1_id":"bandanadee_magic_m",
                    "attackSound2_id":"bandanadee_magic_l",
                    "canFallOff":false,
                    "air_ease":5,
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":-1,
                            "direction":60,
                            "reversableAngle":false,
                            "hitStun":1,
                            "selfHitStun":1,
                            "power":30,
                            "kbConstant":50,
                            "effectSound":"brawl_zap_s",
                            "shock":true
                        }}
                },
                "b_up":{
                    "cancelSoundOnEnd":true,
                    "refreshRate":25,
                    "resetMovement":true,
                    "allowFastFall":false,
                    "xSpeedCap":5,
                    "cancelWhenAirborne":false,
                    "air_ease":0,
                    "canFallOff":false,
                    "attackSound1_id":"bandanadee_uspecSpin",
                    "attackSound2_id":"bandanadee_uspecJump",
                    "attackBoxes":{"attackBox":{
                            "damage":13,
                            "priority":0,
                            "effect_id":"effect_swordSlash",
                            "direction":85,
                            "power":70,
                            "kbConstant":90,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "b_up_air":{
                    "cancelSoundOnEnd":true,
                    "refreshRate":25,
                    "resetMovement":true,
                    "allowFastFall":false,
                    "xSpeedCap":5,
                    "cancelWhenAirborne":false,
                    "air_ease":0,
                    "canFallOff":false,
                    "isRecoveryMove":true,
                    "attackSound1_id":"bandanadee_uspecSpin",
                    "attackSound2_id":"bandanadee_uspecJump",
                    "attackBoxes":{"attackBox":{
                            "damage":13,
                            "priority":0,
                            "effect_id":"effect_swordSlash",
                            "direction":85,
                            "power":70,
                            "kbConstant":80,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "b_forward":{
                    "canFallOff":false,
                    "attackVoice1_id":"ssf2_snd_vfx_bdee_fsmash",
                    "attackSound1_id":"bandanadee_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":23,
                            "priority":6,
                            "camShake":10,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":65,
                            "kbConstant":72,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "b_forward_air":{
                    "allowControl":true,
                    "allowControlGround":false,
                    "attackVoice1_id":"ssf2_snd_vfx_bdee_fsmash",
                    "attackSound1_id":"bandanadee_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":17,
                            "priority":6,
                            "camShake":10,
                            "effect_id":"effect_heavyHit",
                            "direction":35,
                            "power":50,
                            "kbConstant":70,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "b_down":{
                    "resetMovement":true,
                    "refreshRate":-1,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "forceGrabbable":true,
                    "attackVoice1_id":"ssf2_snd_vfx_bdee_dsmash",
                    "attackSound1_id":"bandanadee_swing_l",
                    "attackSound2_id":"bandanadee_dspecSpin",
                    "attackSound3_id":"bandanadee_magic_spin",
                    "attackBoxes":{"attackBox":{
                            "damage":15,
                            "reversableAngle":false,
                            "priority":7,
                            "effect_id":"effect_heavyHit",
                            "direction":70,
                            "power":45,
                            "kbConstant":105,
                            "effectSound":"brawl_zap_l"
                        }}
                },
                "b_down_air":{
                    "resetMovement":true,
                    "refreshRate":2,
                    "cancel":true,
                    "air_ease":2,
                    "canFallOff":false,
                    "forceGrabbable":true,
                    "attackVoice1_id":"ssf2_snd_vfx_bdee_dsmash",
                    "attackSound1_id":"bandanadee_swing_l",
                    "attackSound2_id":"bandanadee_dspecSpin",
                    "attackSound3_id":"bandanadee_magic_spin",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "hitStun":1,
                            "selfHitStun":1,
                            "reversableAngle":false,
                            "priority":7,
                            "effect_id":"effect_heavyHit",
                            "direction":310,
                            "power":40,
                            "kbConstant":70,
                            "effectSound":"brawl_zap_l"
                        }}
                },
                "throw_up":{
                    "canFallOff":false,
                    "refreshRate":3,
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":-1,
                            "hitLag":-1.1,
                            "effect_id":"effect_heavyHit",
                            "direction":85,
                            "power":50,
                            "kbConstant":83,
                            "bypassNonGrabbed":true,
                            "hasEffect":false,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "throw_forward":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":-1,
                            "effect_id":"effect_heavyHit",
                            "direction":63,
                            "reversableAngle":false,
                            "power":40,
                            "kbConstant":75,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "throw_back":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "attackSound1_id":null,
                    "attackSound2_id":"whoosh2",
                    "attackBoxes":{"attackBox":{
                            "forceTumbleFall":true,
                            "damage":8,
                            "priority":-1,
                            "hitLag":-1.1,
                            "effect_id":"effect_heavyHit",
                            "direction":200,
                            "reversableAngle":false,
                            "power":50,
                            "kbConstant":10,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "throw_down":{
                    "canFallOff":false,
                    "cpuAttackQueue":"a_air_down",
                    "attackSound1_id":"brawl_swing_m",
                    "attackSound2_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "bypassNonGrabbed":true,
                            "priority":-1,
                            "hitLag":-1.07,
                            "effect_id":"effect_hit1",
                            "direction":75,
                            "power":40,
                            "kbConstant":110,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "crouch_attack":{
                    "xSpeedDecay":-1,
                    "canFallOff":false,
                    "attackVoice1_id":"ssf2_snd_vfx_bdee_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_bdee_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_bdee_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_bdee_attack04",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":1,
                            "effect_id":"effect_lightHit",
                            "direction":75,
                            "power":35,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "cancelWhenAirborne":false,
                    "maintainSpeed":true,
                    "attackVoice1_id":"ssf2_snd_vfx_bdee_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_bdee_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_bdee_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_bdee_attack04",
                    "attackSound1_id":"bandanadee_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "direction":45,
                            "power":75,
                            "kbConstant":25,
                            "effect_id":"effect_hit2",
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "getup_attack":{
                    "attackSound1_id":"bandanadee_swing_ll",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":0,
                            "weightKB":100,
                            "direction":55,
                            "power":0,
                            "kbConstant":110,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "kirby":{
                    "combo_max":999,
                    "holdRepeat":true,
                    "canFallOff":false,
                    "attackSound1_id":"bandanadee_suck",
                    "attackSound2_id":"bandanadee_spit",
                    "attackSound3_id":"bandanadee_powersteal",
                    "attackSound4_id":"bandanadee_shortsuck",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":0,
                            "direction":30,
                            "power":1,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "kirby_air":{
                    "combo_max":999,
                    "holdRepeat":true,
                    "canFallOff":false,
                    "attackSound1_id":"bandanadee_suck",
                    "attackSound2_id":"bandanadee_spit",
                    "attackSound3_id":"bandanadee_powersteal",
                    "attackSound4_id":"bandanadee_shortsuck",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":0,
                            "direction":30,
                            "power":1,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "special":{
                    "refreshRate":3,
                    "resetMovement":true,
                    "air_ease":0,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "attackSound1_id":"bandanadee_jump1",
                    "attackSound2_id":"bandanadee_land1",
                    "attackSound3_id":"bandanadee_final_start",
                    "cancelWhenAirborne":false,
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "hasEffect":false,
                            "priority":7,
                            "hitStun":12,
                            "selfHitStun":0,
                            "direction":-2,
                            "power":35,
                            "kbConstant":170,
                            "effectSound":null
                        }}
                },
                "item_jab":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_tilt":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_dash":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_smash":{
                    "chargetime_max":40,
                    "chargeClick":true,
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false,
                    "attackVoice1_id":"ssf2_snd_vfx_bdee_attack02"
                },
                "item_homerun":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false,
                    "attackVoice1_id":"ssf2_snd_vfx_bdee_attack03"
                },
                "item_fan":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_shoot":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "canFallOff":false
                },
                "item_heavyshoot":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "canFallOff":false
                },
                "item_raise":{
                    "maintainSpeed":false,
                    "canFallOff":false
                },
                "item_float":{
                    "maintainSpeed":true,
                    "canFallOff":true
                },
                "item_screw":{
                    "refreshRate":1,
                    "allowControl":true,
                    "air_ease":0,
                    "maintainSpeed":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "attackBoxes":{
                        "attackBox":{
                            "damage":1,
                            "priority":5,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":95,
                            "power":125,
                            "kbConstant":10,
                            "stackKnockback":false,
                            "shock":true,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox2":{
                            "damage":1,
                            "priority":5,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":95,
                            "power":125,
                            "kbConstant":10,
                            "stackKnockback":false,
                            "shock":true,
                            "effectSound":"brawl_kick_s"
                        }
                    }
                },
                "item_firedash":{
                    "allowControl":false,
                    "air_ease":0,
                    "maintainSpeed":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "effect_id":"effect_firehit_heavy",
                            "direction":45,
                            "power":25,
                            "kbConstant":110,
                            "burn":true,
                            "effectSound":"brawl_fire_l"
                        }}
                },
                "item_bubblebounce":{
                    "allowControl":true,
                    "air_ease":-1,
                    "maintainSpeed":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "xSpeedCap":6,
                    "xSpeedAccel":0.75,
                    "xSpeedAccelAir":0.75,
                    "xSpeedDecay":0.99,
                    "xSpeedDecayAir":0.99,
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "effect_id":"effect_waterhit_heavy",
                            "direction":270,
                            "power":20,
                            "kbConstant":80,
                            "effectSound":"sfx_waterhit_m"
                        }}
                }
            };
            var _local_3:Object = {
                "dee_nspec":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"dee_nspec",
                    "inheritPalette":true,
                    "width":27,
                    "height":33,
                    "time_max":30,
                    "xspeed":10,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":8,
                                "reversableAngle":false,
                                "priority":0,
                                "hitStun":2,
                                "selfHitStun":2,
                                "effect_id":"effect_swordSlash",
                                "direction":50,
                                "power":80,
                                "kbConstant":75,
                                "effectSound":"brawl_zap_m"
                            }}}
                },
                "dee_spear":{
                    "classAPI":DeeSpearExt,
                    "linkage_id":"dee_spear",
                    "inheritPalette":true,
                    "width":20,
                    "height":5,
                    "time_max":100,
                    "xspeed":8,
                    "yspeed":-15,
                    "gravity":1.5,
                    "maxgravity":24,
                    "rotate":true,
                    "canBeAbsorbed":false,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":5,
                                "reversableAngle":false,
                                "priority":0,
                                "hitStun":11,
                                "selfHitStun":4,
                                "effect_id":"effect_swordSlash",
                                "direction":60,
                                "power":50,
                                "kbConstant":75,
                                "effectSound":"sw_brawl_hit_S"
                            }}}
                },
                "dee_finalsmash":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"dee_finalsmash",
                    "inheritPalette":false,
                    "width":140,
                    "height":140,
                    "xspeed":0,
                    "time_max":480,
                    "rotate":false,
                    "ghost":true,
                    "surviveDeathBounds":true,
                    "canBePocketed":false,
                    "canBeAbsorbed":false,
                    "canBeReversed":false,
                    "attack_idle":{
                        "refreshRate":15,
                        "attackBoxes":{"attackBox":{
                                "damage":4,
                                "priority":-1,
                                "hitStun":3,
                                "selfHitStun":1,
                                "direction":55,
                                "power":90,
                                "kbConstant":120,
                                "bypassShield":true,
                                "bypassHeavyArmor":true,
                                "bypassSuperArmor":true,
                                "effectSound":"bdee_fs_hit",
                                "shock":true,
                                "effect_id":"fs_hit"
                            }}
                    }
                }
            };
            var _local_4:Object;
            return {
                "cData":_local_1,
                "aData":_local_2,
                "pData":_local_3,
                "iData":_local_4
            };
        }


    }
}

