package
{
    public dynamic class Main extends SSF2Asset
    {

        public function Main()
        {
            super();
            register("id", "dedede");
            register("guid", "02d29602-d514-4a98-8ac2-6afd498f3323");
            register("resources", {
                "movieclips":[],
                "sounds":[]
            });
            register("characters", [this.getDedede()]);
        }

        public function getDedede():Object
        {
            var _local_1:Object = new Object();
            _local_1 = {
                "classAPI":DededeExt,
                "statsName":"dedede",
                "displayName":"King Dedede",
                "linkage_id":"dedede",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"dedede_head",
                "seriesIcon":"Kirby_Symbol",
                "width":50,
                "height":66,
                "shield_scale":1.4,
                "shield_y_offset":5,
                "shield_x_offset":-6,
                "jumpSpeed":17,
                "jumpStartup":3,
                "shortHopSpeed":11,
                "max_jumpSpeed":6,
                "groundToAirMultiplier":0.833,
                "midAirTurn":true,
                "dodgeSpeed":16.5,
                "dodgeDecel":-1.2,
                "weight1":112,
                "power":"dedede",
                "norm_xSpeed":3.8,
                "max_xSpeed":8.4,
                "accel_start":1,
                "accel_start_dash":1.1,
                "accel_rate":1.5,
                "accel_rate_air":0.5,
                "decel_rate":-0.97,
                "decel_rate_air":-0.15,
                "holdJump":true,
                "max_projectile":10,
                "tetherGrab":false,
                "roll_speed":32,
                "roll_decay":0.7,
                "getup_roll_delay":5,
                "tech_roll_delay":4,
                "climb_roll_delay":8,
                "itemScaleRatio":0.69,
                "special_type":2,
                "finalSmashCutin":"ddd_fs_cutin",
                "normalStats_id":"dedede",
                "specialStats_id":null,
                "max_jump":4,
                "jumpSpeedList":"14,13,12,11",
                "gravity":1.3,
                "max_ySpeed":11,
                "fastFallSpeed":15,
                "sounds":{
                    "jump":null,
                    "jump_midair":null,
                    "hurt":"ssf2_snd_vfx_dedede_hurt01",
                    "hurt2":"ssf2_snd_vfx_dedede_hurt02",
                    "hurtBad":"ssf2_snd_vfx_dedede_hurtBad01",
                    "hurtBad2":"ssf2_snd_vfx_dedede_hurtBad02",
                    "dead":"ssf2_snd_vfx_dedede_dead01",
                    "dead2":"ssf2_snd_vfx_dedede_dead02",
                    "pummel":"brawl_kick_s",
                    "screenko":"ssf2_snd_vfx_dedede_hurtBad01",
                    "starko":"ssf2_snd_vfx_dedede_starKO",
                    "ledge_grab":"ssf2_snd_vfx_dedede_edgeGrab",
                    "winTheme":"KirbyVictory"
                },
                "hurtFrames":4,
                "grabDamage":3
            };
            var _local_2:Object = new Object();
            _local_2 = {
                "a":{
                    "refreshRate":100,
                    "xSpeedDecay":-0.95,
                    "canFallOff":false,
                    "attackVoice1_id":"ssf2_snd_vfx_dedede_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_dedede_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_dedede_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_dedede_attack04",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":4,
                            "hitStun":3,
                            "selfHitStun":1,
                            "hitLag":-1.1,
                            "effect_id":"effect_hit2",
                            "direction":75,
                            "power":10,
                            "kbConstant":40,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_m"
                        },
                        "attackBox2":{
                            "damage":4,
                            "hitStun":3,
                            "selfHitStun":1,
                            "hitLag":-1.1,
                            "effect_id":"effect_hit2",
                            "direction":75,
                            "power":10,
                            "kbConstant":40,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_m"
                        }
                    }
                },
                "a_up":{
                    "chargetime_max":40,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"ssf2_snd_vfx_dedede_usmash",
                    "attackBoxes":{
                        "attackBox":{
                            "camShake":10,
                            "damage":14,
                            "hitStun":8,
                            "selfHitStun":6,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "power":40,
                            "kbConstant":96,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_m"
                        },
                        "attackBox2":{
                            "camShake":10,
                            "damage":14,
                            "hitStun":8,
                            "selfHitStun":6,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "power":40,
                            "kbConstant":96,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_m"
                        },
                        "attackBox3":{
                            "camShake":10,
                            "damage":14,
                            "hitStun":8,
                            "selfHitStun":6,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "power":40,
                            "kbConstant":96,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_m"
                        },
                        "attackBox4":{
                            "camShake":10,
                            "damage":9,
                            "hitStun":8,
                            "selfHitStun":6,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "power":40,
                            "kbConstant":96,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_m"
                        }
                    }
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"ssf2_snd_vfx_dedede_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_dedede_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_dedede_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_dedede_attack04",
                    "attackBoxes":{
                        "attackBox":{
                            "camShake":10,
                            "damage":12,
                            "hitStun":6,
                            "selfHitStun":3,
                            "effect_id":"effect_hit1",
                            "direction":96,
                            "power":50,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox2":{
                            "camShake":10,
                            "damage":10,
                            "hitStun":6,
                            "selfHitStun":3,
                            "effect_id":"effect_hit1",
                            "direction":96,
                            "power":50,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox3":{
                            "camShake":10,
                            "damage":10,
                            "hitStun":6,
                            "selfHitStun":3,
                            "effect_id":"effect_hit1",
                            "direction":96,
                            "power":50,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_l"
                        }
                    }
                },
                "a_forward":{
                    "canFallOff":false,
                    "attackBoxes":{"attackBox":{
                            "reversableAngle":false,
                            "damage":16,
                            "hitStun":5,
                            "hitLag":-1,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":35,
                            "power":40,
                            "kbConstant":100,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_ll"
                        }}
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"ssf2_snd_vfx_dedede_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_dedede_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_dedede_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_dedede_attack04",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":2,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "reversableAngle":false,
                            "direction":20,
                            "power":70,
                            "kbConstant":0,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_s"
                        },
                        "attackBox2":{
                            "damage":2,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":20,
                            "power":45,
                            "kbConstant":0,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_s"
                        },
                        "attackBox3":{
                            "damage":2,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":120,
                            "power":30,
                            "kbConstant":0,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_s"
                        },
                        "attackBox4":{
                            "damage":2,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":210,
                            "power":30,
                            "kbConstant":0,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_s"
                        }
                    }
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"ssf2_snd_vfx_dedede_fsmash",
                    "attackBoxes":{
                        "attackBox":{
                            "camShake":15,
                            "damage":18,
                            "hitStun":10,
                            "selfHitStun":8,
                            "effect_id":"effect_heavyHit",
                            "direction":40,
                            "power":40,
                            "kbConstant":95,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_ll"
                        },
                        "attackBox2":{
                            "camShake":15,
                            "damage":18,
                            "hitStun":10,
                            "selfHitStun":8,
                            "effect_id":"effect_heavyHit",
                            "direction":40,
                            "power":40,
                            "kbConstant":95,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_ll"
                        },
                        "attackBox3":{
                            "camShake":15,
                            "damage":18,
                            "hitStun":10,
                            "selfHitStun":8,
                            "effect_id":"effect_heavyHit",
                            "direction":40,
                            "power":40,
                            "kbConstant":95,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_ll"
                        }
                    }
                },
                "a_down":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"ssf2_snd_vfx_dedede_dsmash",
                    "attackBoxes":{
                        "attackBox":{
                            "camShake":7,
                            "damage":14,
                            "hitStun":6,
                            "selfHitStun":4,
                            "effect_id":"effect_heavyHit",
                            "direction":40,
                            "power":60,
                            "kbConstant":80,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_m"
                        },
                        "attackBox2":{
                            "camShake":12,
                            "damage":13,
                            "hitStun":9,
                            "selfHitStun":7,
                            "effect_id":"effect_heavyHit",
                            "direction":30,
                            "power":60,
                            "kbConstant":80,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_m"
                        }
                    }
                },
                "a_air":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"ssf2_snd_vfx_dedede_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_dedede_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_dedede_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_dedede_attack04",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":12,
                            "hitStun":4,
                            "hitLag":-1.15,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "power":40,
                            "kbConstant":95,
                            "effectSound":"brawl_punch_l"
                        },
                        "attackBox2":{
                            "damage":12,
                            "hitStun":4,
                            "hitLag":-1.15,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "power":40,
                            "kbConstant":95,
                            "effectSound":"brawl_punch_l"
                        }
                    }
                },
                "a_air_up":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"ssf2_snd_vfx_dedede_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_dedede_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_dedede_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_dedede_attack04",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":2,
                            "hitStun":0,
                            "hitLag":10,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":90,
                            "reversableAngle":false,
                            "power":0,
                            "kbConstant":0,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_s"
                        },
                        "attackBox2":{
                            "damage":2,
                            "hitStun":0,
                            "hitLag":10,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":90,
                            "reversableAngle":false,
                            "power":0,
                            "kbConstant":0,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_s"
                        }
                    }
                },
                "a_air_forward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"ssf2_snd_vfx_dedede_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_dedede_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_dedede_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_dedede_attack04",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":16,
                            "hitStun":7,
                            "selfHitStun":6,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":30,
                            "kbConstant":100,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_l"
                        },
                        "attackBox2":{
                            "damage":16,
                            "hitStun":7,
                            "selfHitStun":6,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":30,
                            "kbConstant":100,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_l"
                        }
                    }
                },
                "a_air_backward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"ssf2_snd_vfx_dedede_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_dedede_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_dedede_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_dedede_attack04",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":12,
                            "hitStun":5,
                            "selfHitStun":4,
                            "effect_id":"effect_heavyHit",
                            "direction":35,
                            "power":35,
                            "kbConstant":95,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_m"
                        },
                        "attackBox2":{
                            "damage":12,
                            "hitStun":5,
                            "selfHitStun":4,
                            "effect_id":"effect_heavyHit",
                            "direction":35,
                            "power":35,
                            "kbConstant":95,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_m"
                        },
                        "attackBox3":{
                            "damage":13,
                            "hitStun":6,
                            "selfHitStun":5,
                            "effect_id":"effect_heavyHit",
                            "direction":35,
                            "power":35,
                            "kbConstant":95,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_m"
                        }
                    }
                },
                "a_air_down":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"ssf2_snd_vfx_dedede_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_dedede_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_dedede_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_dedede_attack04",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":15,
                            "hitStun":6,
                            "selfHitStun":5,
                            "effect_id":"effect_heavyHit",
                            "direction":270,
                            "power":30,
                            "kbConstant":100,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_ll"
                        },
                        "attackBox2":{
                            "damage":15,
                            "hitStun":6,
                            "selfHitStun":5,
                            "effect_id":"effect_heavyHit",
                            "direction":270,
                            "power":30,
                            "kbConstant":100,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_ll"
                        }
                    }
                },
                "b":{
                    "reenableTimer":-1,
                    "xSpeedCap":4,
                    "refreshRate":5,
                    "combo_max":999,
                    "holdRepeat":true,
                    "attackSound1_id":"ssf2_snd_sfx_dedede_nspec_start",
                    "attackSound2_id":"ssf2_snd_sfx_dedede_nspec_loop",
                    "attackSound3_id":"ssf2_snd_sfx_dedede_nspec_end",
                    "attackSound4_id":"ssf2_snd_sfx_dedede_nspec_grab",
                    "attackSound5_id":"ssf2_snd_sfx_dedede_jump01",
                    "attackSound6_id":"ssf2_snd_sfx_dedede_landHeavy",
                    "attackSound7_id":"ssf2_snd_sfx_dedede_nspec_spit",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "hasEffect":false,
                            "sdiDistance":0,
                            "hitStun":4,
                            "selfHitStun":0,
                            "direction":150,
                            "reversableAngle":false,
                            "power":60,
                            "kbConstant":9,
                            "bypassShield":true,
                            "effectSound":null
                        }}
                },
                "b_air":{
                    "reenableTimer":-1,
                    "xSpeedCap":4,
                    "refreshRate":5,
                    "combo_max":999,
                    "holdRepeat":true,
                    "attackSound1_id":"ssf2_snd_sfx_dedede_nspec_start",
                    "attackSound2_id":"ssf2_snd_sfx_dedede_nspec_loop",
                    "attackSound3_id":"ssf2_snd_sfx_dedede_nspec_end",
                    "attackSound4_id":"ssf2_snd_sfx_dedede_nspec_grab",
                    "attackSound5_id":"ssf2_snd_sfx_dedede_jump01",
                    "attackSound6_id":"ssf2_snd_sfx_dedede_landHeavy",
                    "attackSound7_id":"ssf2_snd_sfx_dedede_nspec_spit",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "hasEffect":false,
                            "sdiDistance":0,
                            "hitStun":4,
                            "selfHitStun":0,
                            "direction":150,
                            "reversableAngle":false,
                            "power":60,
                            "kbConstant":9,
                            "bypassShield":true,
                            "effectSound":null
                        }}
                },
                "b_up":{
                    "air_ease":0,
                    "allowControl":false,
                    "maintainSpeed":true,
                    "cancelWhenAirborne":false,
                    "isRecoveryMove":true,
                    "attackVoice1_id":"ssf2_snd_vfx_dedede_uspec_start",
                    "attackVoice2_id":"ssf2_snd_vfx_dedede_uspec_land",
                    "attackSound1_id":"ssf2_snd_sfx_dedede_uspec_rise",
                    "attackSound2_id":"ssf2_snd_sfx_dedede_uspec_land",
                    "attackSound3_id":"ssf2_snd_sfx_dedede_uspec_fail",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":15,
                            "hitStun":3,
                            "selfHitStun":3,
                            "pitfall":30,
                            "effect_id":"effect_hit2",
                            "direction":270,
                            "power":90,
                            "kbConstant":90,
                            "effectSound":"sw_brawl_hit_S",
                            "hitLag":-0.8
                        },
                        "attackBox2":{
                            "damage":12,
                            "hitStun":3,
                            "selfHitStun":3,
                            "effect_id":"effect_hit2",
                            "direction":50,
                            "power":70,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_m",
                            "hitLag":-0.8
                        },
                        "attackBox3":{
                            "damage":12,
                            "hitStun":3,
                            "selfHitStun":3,
                            "effect_id":"effect_hit2",
                            "direction":50,
                            "power":70,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_m",
                            "hitLag":-0.8
                        }
                    }
                },
                "b_up_air":{
                    "air_ease":0,
                    "allowControl":false,
                    "maintainSpeed":true,
                    "cancelWhenAirborne":false,
                    "isRecoveryMove":true,
                    "attackVoice1_id":"ssf2_snd_vfx_dedede_uspec_start",
                    "attackVoice2_id":"ssf2_snd_vfx_dedede_uspec_land",
                    "attackSound1_id":"ssf2_snd_sfx_dedede_uspec_rise",
                    "attackSound2_id":"ssf2_snd_sfx_dedede_uspec_land",
                    "attackSound3_id":"ssf2_snd_sfx_dedede_uspec_fail",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":15,
                            "hitStun":3,
                            "selfHitStun":3,
                            "pitfall":30,
                            "effect_id":"effect_hit2",
                            "direction":270,
                            "power":90,
                            "kbConstant":90,
                            "effectSound":"sw_brawl_hit_S",
                            "hitLag":-0.8
                        },
                        "attackBox2":{
                            "damage":12,
                            "hitStun":3,
                            "selfHitStun":3,
                            "effect_id":"effect_hit2",
                            "direction":50,
                            "power":70,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_m",
                            "hitLag":-0.8
                        },
                        "attackBox3":{
                            "damage":12,
                            "hitStun":3,
                            "selfHitStun":3,
                            "effect_id":"effect_hit2",
                            "direction":50,
                            "power":70,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_m",
                            "hitLag":-0.8
                        }
                    }
                },
                "b_forward":{
                    "cancelWhenAirborne":false,
                    "reenableTimer":20,
                    "canFallOff":false,
                    "allowFastFall":false,
                    "allowControl":false,
                    "chargeInAir":false,
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "reversableAngle":false,
                            "priority":1,
                            "hitStun":2,
                            "hitLag":-1.22,
                            "selfHitStun":1,
                            "direction":40,
                            "power":90,
                            "kbConstant":30,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "b_forward_air":{
                    "isHorizontalRecoveryMove":false,
                    "reenableTimer":20,
                    "cancelWhenAirborne":false,
                    "chargeInAir":false,
                    "allowFastFall":false,
                    "allowControl":false,
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "reversableAngle":false,
                            "priority":1,
                            "hitStun":2,
                            "hitLag":-1.22,
                            "selfHitStun":1,
                            "direction":40,
                            "power":90,
                            "kbConstant":30,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "b_down":{
                    "cancelWhenAirborne":false,
                    "attackBoxes":{
                        "attackBox":{
                            "damage":120,
                            "priority":7,
                            "hitStun":3,
                            "selfHitStun":3,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":60,
                            "kbConstant":50,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_l"
                        },
                        "attackBox2":{
                            "damage":400,
                            "priority":7,
                            "hitStun":6,
                            "selfHitStun":6,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":60,
                            "kbConstant":50,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_m"
                        }
                    }
                },
                "b_down_air":{
                    "cancelWhenAirborne":false,
                    "attackBoxes":{
                        "attackBox":{
                            "damage":110,
                            "priority":7,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":60,
                            "kbConstant":50,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_l"
                        },
                        "attackBox2":{
                            "damage":320,
                            "priority":7,
                            "hitStun":5,
                            "selfHitStun":5,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":60,
                            "kbConstant":50,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_m"
                        }
                    }
                },
                "throw_up":{
                    "canFallOff":false,
                    "attackVoice1_id":"ssf2_snd_vfx_dedede_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_dedede_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_dedede_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_dedede_attack04",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "bypassGrabbed":true,
                            "direction":45,
                            "power":60,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_l",
                            "effect_id":"effect_heavyHit"
                        },
                        "attackBox2":{
                            "damage":6,
                            "bypassNonGrabbed":true,
                            "hitStun":2,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "direction":85,
                            "reversableAngle":false,
                            "power":60,
                            "kbConstant":80,
                            "effect_id":"effect_hit1",
                            "effectSound":"brawl_punch_l"
                        }
                    }
                },
                "throw_forward":{
                    "canFallOff":false,
                    "attackVoice1_id":"ssf2_snd_vfx_dedede_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_dedede_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_dedede_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_dedede_attack04",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "bypassGrabbed":true,
                            "direction":45,
                            "power":60,
                            "kbConstant":100,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_s",
                            "effect_id":"effect_heavyHit"
                        },
                        "attackBox2":{
                            "damage":8,
                            "bypassNonGrabbed":true,
                            "hitLag":-1.12,
                            "direction":50,
                            "reversableAngle":false,
                            "power":75,
                            "kbConstant":85,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "effectSound":"ssf2_snd_sfx_dedede_hit_l"
                        }
                    }
                },
                "throw_back":{
                    "canFallOff":false,
                    "attackVoice1_id":"ssf2_snd_vfx_dedede_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_dedede_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_dedede_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_dedede_attack04",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "bypassGrabbed":true,
                            "direction":45,
                            "power":40,
                            "kbConstant":90,
                            "effectSound":"ssf2_snd_sfx_dedede_hit_s",
                            "effect_id":"effect_heavyHit"
                        },
                        "attackBox2":{
                            "damage":9,
                            "bypassNonGrabbed":true,
                            "hitStun":3,
                            "hitLag":-1,
                            "selfHitStun":2,
                            "direction":120,
                            "reversableAngle":false,
                            "power":40,
                            "kbConstant":80,
                            "effect_id":"effect_hit2",
                            "effectSound":"ssf2_snd_sfx_dedede_hit_l"
                        }
                    }
                },
                "throw_down":{
                    "canFallOff":false,
                    "attackVoice1_id":"ssf2_snd_vfx_dedede_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_dedede_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_dedede_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_dedede_attack04",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "hitStun":4,
                            "selfHitStun":3,
                            "direction":80,
                            "reversableAngle":false,
                            "power":65,
                            "kbConstant":75,
                            "bypassNonGrabbed":true,
                            "effect_id":"effect_hit2",
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "crouch_attack":{
                    "canFallOff":false,
                    "attackVoice1_id":"ssf2_snd_vfx_dedede_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_dedede_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_dedede_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_dedede_attack04",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":45,
                            "reversableAngle":false,
                            "power":60,
                            "kbConstant":75,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackVoice1_id":"ssf2_snd_vfx_dedede_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_dedede_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_dedede_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_dedede_attack04",
                    "attackSound1_id":"ssf2_snd_sfx_dedede_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "direction":45,
                            "power":75,
                            "kbConstant":25,
                            "effect_id":"effect_hit2",
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "getup_attack":{
                    "canFallOff":false,
                    "attackVoice1_id":"ssf2_snd_vfx_dedede_attack01",
                    "attackVoice2_id":"ssf2_snd_vfx_dedede_attack02",
                    "attackVoice3_id":"ssf2_snd_vfx_dedede_attack03",
                    "attackVoice4_id":"ssf2_snd_vfx_dedede_attack04",
                    "attackSound1_id":"ssf2_snd_sfx_dedede_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":2,
                            "hitStun":3,
                            "weightKB":100,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":25,
                            "power":0,
                            "kbConstant":110,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "kirby":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "canFallOff":false,
                    "chargeInAir":false,
                    "canUseInAir":true,
                    "attackVoice1_id":"Kirby_Attack01",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "hitStun":3,
                            "hitLag":0.45,
                            "selfHitStun":0,
                            "direction":10,
                            "power":-1000,
                            "kbConstant":16,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "kirby_air":{
                    "refreshRate":1000,
                    "allowControl":false,
                    "chargeInAir":false,
                    "canUseInAir":true,
                    "reenableTimer":3000,
                    "attackVoice1_id":"Kirby_Attack01",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "hitStun":3,
                            "hitLag":0.45,
                            "selfHitStun":0,
                            "direction":10,
                            "power":-1000,
                            "kbConstant":16,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "special":{
                    "refreshRate":1000,
                    "canFallOff":false,
                    "grabBehind":true,
                    "xSpeedCap":3.5,
                    "xSpeedDecay":0.25,
                    "xSpeedDecayAir":0.25,
                    "allowControlGround":false,
                    "allowControl":false,
                    "cancelWhenAirborne":false,
                    "air_ease":0,
                    "canUseInAir":true,
                    "attackBoxes":{
                        "attackBox":{
                            "damage":4,
                            "hitStun":6,
                            "hitLag":-1.4,
                            "priority":-1,
                            "selfHitStun":0,
                            "direction":90,
                            "power":20,
                            "kbConstant":0,
                            "hasEffect":false,
                            "bypassNonGrabbed":true,
                            "shock":true,
                            "effect_id":"effect_heavyHit",
                            "effectSound":"ssf2_snd_sfx_dedede_hit_m"
                        },
                        "attackBox2":{
                            "damage":4,
                            "canDI":false,
                            "hitStun":1,
                            "priority":-1,
                            "weightKB":100,
                            "selfHitStun":0,
                            "direction":135,
                            "power":0,
                            "kbConstant":120,
                            "reversableAngle":false,
                            "hasEffect":true,
                            "bypassGrabbed":true,
                            "shock":true,
                            "effect_id":"effect_heavyHit",
                            "effectSound":"ssf2_snd_sfx_dedede_hit_m"
                        }
                    }
                },
                "item_jab":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_tilt":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_dash":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_smash":{
                    "chargetime_max":40,
                    "chargeClick":true,
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false,
                    "attackVoice1_id":"ssf2_snd_vfx_dedede_attack04"
                },
                "item_homerun":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false,
                    "attackVoice1_id":"dedede_fsmash"
                },
                "item_fan":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":false,
                    "canUseInAir":false
                },
                "item_shoot":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "canFallOff":false
                },
                "item_heavyshoot":{
                    "allowControl":false,
                    "maintainSpeed":false,
                    "canFallOff":false
                },
                "item_raise":{
                    "maintainSpeed":false,
                    "canFallOff":false
                },
                "item_float":{
                    "maintainSpeed":true,
                    "canFallOff":true
                },
                "item_screw":{
                    "refreshRate":1,
                    "allowControl":true,
                    "air_ease":0,
                    "maintainSpeed":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "attackBoxes":{
                        "attackBox":{
                            "damage":1,
                            "priority":5,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":95,
                            "power":125,
                            "kbConstant":10,
                            "stackKnockback":false,
                            "shock":true,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox2":{
                            "damage":1,
                            "priority":5,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":95,
                            "power":125,
                            "kbConstant":10,
                            "stackKnockback":false,
                            "shock":true,
                            "effectSound":"brawl_kick_s"
                        }
                    }
                },
                "item_firedash":{
                    "allowControl":false,
                    "air_ease":0,
                    "maintainSpeed":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "effect_id":"effect_firehit_heavy",
                            "direction":45,
                            "power":25,
                            "kbConstant":110,
                            "burn":true,
                            "effectSound":"brawl_fire_l"
                        }}
                },
                "item_bubblebounce":{
                    "allowControl":true,
                    "air_ease":-1,
                    "maintainSpeed":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "xSpeedCap":6,
                    "xSpeedAccel":0.75,
                    "xSpeedAccelAir":0.75,
                    "xSpeedDecay":0.99,
                    "xSpeedDecayAir":0.99,
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "effect_id":"effect_waterhit_heavy",
                            "direction":270,
                            "power":20,
                            "kbConstant":80,
                            "effectSound":"sfx_waterhit_m"
                        }}
                }
            };
            var _local_3:Object = {
                "dedede_starbullet":{"classAPI":StarBullet},
                "dedede_jump_star":{
                    "linkage_id":"dedede_jump_star",
                    "classAPI":SSF2Projectile,
                    "canBeReversed":true,
                    "canBeAbsorbed":true,
                    "height":18,
                    "limit":4,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":5,
                                "hitStun":1,
                                "selfHitStun":1,
                                "direction":70,
                                "power":20,
                                "kbConstant":65,
                                "reversableAngle":false,
                                "effect_id":"effect_swordSlash",
                                "effectSound":"sw_brawl_hit_S"
                            }}}
                },
                "dedede_gordo":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"dedede_gordo",
                    "width":35,
                    "height":35,
                    "time_max":140,
                    "gravity":1.5,
                    "maxgravity":20,
                    "canBeReversed":true,
                    "canReceiveHits":true,
                    "limit":1,
                    "inheritPalette":true,
                    "limitOverwrite":false,
                    "attack_idle":{"attackBoxes":{
                            "attackBox":{
                                "damage":14,
                                "priority":-1,
                                "direction":45,
                                "power":60,
                                "kbConstant":60,
                                "hitStun":8,
                                "selfHitStun":8,
                                "effect_id":"effect_lightHit",
                                "effectSound":"brawl_kick_m"
                            },
                            "attackBox2":{
                                "damage":14,
                                "priority":-1,
                                "direction":45,
                                "power":60,
                                "kbConstant":60,
                                "hitStun":8,
                                "selfHitStun":8,
                                "effect_id":"effect_lightHit",
                                "effectSound":"brawl_kick_m"
                            }
                        }}
                },
                "homingmissile":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"ddd_missile",
                    "width":27,
                    "inheritPalette":true,
                    "rideGround":true,
                    "height":17,
                    "time_max":210,
                    "xdecay":0.15,
                    "ghost":true,
                    "trailEffect":"missileTrail",
                    "trailEffectRotate":true,
                    "trailEffectInterval":1,
                    "homingSpeed":36,
                    "homingEase":5,
                    "xspeed":30,
                    "rotate":true,
                    "rideGround":false,
                    "xoffset":32,
                    "yoffset":-45,
                    "canBeAbsorbed":false,
                    "canBePocketed":false,
                    "lockSize":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":5,
                                "priority":-1,
                                "hitStun":1,
                                "selfHitStun":-1,
                                "hitLag":-1.4,
                                "camShake":5,
                                "effect_id":null,
                                "direction":50,
                                "reversableAngle":false,
                                "weightKB":125,
                                "power":0,
                                "kbConstant":65,
                                "forceTumbleFall":true,
                                "burn":true,
                                "effect_id":"effect_firehit_light",
                                "effectSound":"brawl_fire_l"
                            }}}
                },
                "bigHomingMissile":{
                    "classAPI":SSF2Projectile,
                    "linkage_id":"ddd_bigMissile",
                    "width":27,
                    "inheritPalette":true,
                    "rideGround":true,
                    "height":17,
                    "time_max":210,
                    "xdecay":0.15,
                    "ghost":true,
                    "trailEffect":"missileTrail",
                    "trailEffectRotate":true,
                    "trailEffectInterval":1,
                    "homingSpeed":36,
                    "homingEase":5,
                    "xspeed":28,
                    "rotate":true,
                    "rideGround":false,
                    "xoffset":32,
                    "yoffset":-45,
                    "canBeAbsorbed":false,
                    "canBePocketed":false,
                    "lockSize":true,
                    "attack_idle":{"attackBoxes":{
                            "attackBox":{
                                "damage":10,
                                "priority":-1,
                                "hitStun":10,
                                "selfHitStun":-1,
                                "camShake":10,
                                "direction":50,
                                "reversableAngle":false,
                                "power":65,
                                "kbConstant":100,
                                "forceTumbleFall":true,
                                "burn":true,
                                "effect_id":"effect_firehit_heavy",
                                "effectSound":"bombexplode"
                            },
                            "attackBox2":{
                                "damage":10,
                                "priority":-1,
                                "hitStun":10,
                                "selfHitStun":-1,
                                "camShake":10,
                                "direction":50,
                                "reversableAngle":false,
                                "power":65,
                                "kbConstant":100,
                                "forceTumbleFall":true,
                                "burn":true,
                                "effect_id":"effect_firehit_heavy",
                                "effectSound":"bombexplode"
                            },
                            "attackBox3":{
                                "damage":10,
                                "priority":-1,
                                "hitStun":10,
                                "selfHitStun":-1,
                                "camShake":10,
                                "direction":50,
                                "reversableAngle":false,
                                "power":65,
                                "kbConstant":100,
                                "forceTumbleFall":true,
                                "burn":true,
                                "effect_id":"effect_firehit_heavy",
                                "effectSound":"bombexplode"
                            }
                        }}
                }
            };
            var _local_4:Object;
            return {
                "cData":_local_1,
                "aData":_local_2,
                "pData":_local_3,
                "iData":_local_4
            };
        }


    }
}

